<?PHP
// $Id: config-reqcr.php 3129 2017-08-11 18:55:26Z hjackson $
// Service configuration file
//    xsvc-reqcr.xas?id=tokenacid

require_once("../../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "reqcrresult";
$_service_version = "1.3";

$_allow_upn_override = true;

// domain extension for UPN
$_upn_domain = "@xtec.com";

// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : multiple instance attribute. Signifies that the attribute is not to be replaced
//  0x02 : 
//  0x04 : date format conversion required from/to openldap format and MM-DD-YYYY format
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_db_elements = array (
"credential:belongsto:credential|belongsto|x|txt:txt|0x00",
"entity:firstname:entity|firstname|x|txt:txt|0x00",
"entity:mi:entity|mi|x|txt:txt|0x00",
"entity:lastname:entity|lastname|x|txt:txt|0x00",
"entity:suffix:entity|suffix|x|txt:txt|0x00",
"entity:ediident:entity|ediident|x|txt:txt|0x00",
"entity:upn:entity|upn|x|txt:txt|0x00",
"entity:emplid=usaccess:email:employment|officeemail|x|txt:txt|0x00",
"token:upn:credential|tupn|x|txt:txt|0x00",
"token:tokenclass:credential|tokenclass|x|txt:txt|0x00",
"token:gcoid=A000000308.5fc102:xblk:000030:gco|altname|x|txt:txt|0x00",  // fascn
"token:gcoid=A000000308.5fc102:xblk:000030:gco|fascn|x|txt:txt|0x00",  // fascn
"token:gcoid=A000000308.5fc102:xblk:000034:gco|guid|x|txt:txt|0x00",
"token:gcoid=A000000308.5fc102:xblk:000035:gco|expdate|x|txt:txt|0x00",
"entity:gcoid=general:xblk:002502:gco|affiliation|x|txt:txt|0x00",
"entity:gcoid=general:xblk:002510:gco|upnorg|x|txt:txt|0x00",
"entity:gcoid=general:xblk:002511:gco|orgimp|x|txt:txt|0x00",
"entity:gcoid=general:xblk:002512:gco|upnimport|x|txt:txt|0x00",
"token:gcoid=card:xblk:000088:gco|upnextension|x|txt:txt|0x00",
"entity:gcoid=token,procid=token,ounit=dac:xblk:000054:gco|devicetype|x|txt:txt|0x00",
);

$_constant_elements = array (
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, keyflags) ),
// );
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server, '0': key generated by token.
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_key_map = array (
"A000000308" => array (
"9A" => array("5FC105", 0x00),
"9C" => array("5FC10A", 0x00),
"9D" => array("5FC10B", 0x00),
),
);

$_keyUsage = array (
// new - used with 27K Entrust CA
"9A" => "9A",
"9C" => "9C",
"9D" => "9D",
);

// extension_flags: Bits to signify extensions to include in cert request
// NOTE: each cert must have at least one subjAltName
//  0x00 : nada
//  0x01 : FASCN as subject alternative name
//  0x02 : UPN as subject alternative name
//  0x04 : email address as subject alternative name
//  0x08 :
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_certExtensions = array (
"9A" => 0x07,
"9C" => 0x04, // 0x04
"9D" => 0x04, // 0x04
);

$_baseDNconfig_pivi = array  // for testing
(
	array("\x55\x04\x06", "c",  "US"),					// country
	array("\x55\x04\x0b", "ou", "XTec PIV-I SSP"),		// orgunit1
	array("\x55\x04\x0a", "o",  "XTec PIV-I Customers-General"), 	// org
//	array("\x55\x04\x0b", "ou", "Unaffiliated"), 
	array("\x55\x04\x0b", "ou", "Users"), 				// orgunit2
);


if(!isset($_debug))
	$_debug = true;

if(!isset($logsdir))
        $logsdir = '/authentxlogs/debug';

?>
