<?PHP
// $Id: config-keymaps.php 422 2008-06-29 04:36:40Z atlas $
// Service configuration file
// This configuration file gets called by the initcard and pivencode webservices.

$_service_envelope = "keymaps";
$_service_version = "1.2";

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $algorithmid
// $_key_map[$appletid][$keyid][2] = $keyflags

// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, algorithmid, keyflags) ),
// );

// keyid:
// 9A: PIV Authentication Certificate
// 9C: Signature Certificate
// 9D: Encryption Certificate -- flagged for escrow
// 9E: Card Authentication Certificate (currently not requested)

// certcontainer:
// working list (need to define better/see what they mean
// 5FC105: ?
// 5FC10A: ?
// 5FC10B: ?
// 5FC101: ?

// algorithmid:
// 0x01: 3DES-16bytekey-ECB
// 0x06: RSA-1024
// 0x07: RSA-2048

// keyflags: Bits to signify key features
//  0x01 : '1': key generated by server (escrow), '0': key generated by token (token).
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_key_map_yubikey = array (
"A00000030800001000" => array (
	"9A" => array("5FC105", 0x07, 0x00),
	"9C" => array("5FC10A", 0x07, 0x00),
	"9D" => array("5FC10B", 0x07, 0x01), //need to escrow this key and inject it [gemalto]
	)
);

$_key_map = array (
"A00000030800001000" => array (
	"9A" => array("5FC105", 0x07, 0x00),
	"9C" => array("5FC10A", 0x07, 0x00),
	"9D" => array("5FC10B", 0x07, 0x01), //need to escrow this key and inject it [gemalto]
	)
);


// archived escrow keys
$_key_map_escrow = array (	
"A00000030800001000" => array (
        "9A" => array("5FC105", 0x07, 0x00),
        "9C" => array("5FC10A", 0x07, 0x00),
        "9D" => array("5FC10B", 0x07, 0x01),

		"82" => array("5FC10D", 0x07, 0x01),
		"83" => array("5FC10E", 0x07, 0x01),
		"84" => array("5FC10F", 0x07, 0x01),
		"85" => array("5FC110", 0x07, 0x01),
		"86" => array("5FC111", 0x07, 0x01),

		"87" => array("5FC112", 0x07, 0x01),
		"88" => array("5FC113", 0x07, 0x01),
		"89" => array("5FC114", 0x07, 0x01),
		"8A" => array("5FC115", 0x07, 0x01),
		"8B" => array("5FC116", 0x07, 0x01),

		"8C" => array("5FC117", 0x07, 0x01),
		"8D" => array("5FC118", 0x07, 0x01),
		"8E" => array("5FC119", 0x07, 0x01),
		"8F" => array("5FC11A", 0x07, 0x01),
		"90" => array("5FC11B", 0x07, 0x01),

		"91" => array("5FC11C", 0x07, 0x01),
		"92" => array("5FC11D", 0x07, 0x01),
		"93" => array("5FC11E", 0x07, 0x01),
		"94" => array("5FC11F", 0x07, 0x01),
		"95" => array("5FC120", 0x07, 0x01),
	)
);

if (!defined("KEYFLAGS_ESCROW"))
	define("KEYFLAGS_ESCROW", 0x01);

$_cardconfigs = <<<CARDCONFIG
<?xml version="1.0"?>
<configcard>
		<cardinfo name="oberthurv8.1" cardid="3033333039">
				<opcodes xmlname="defaultCMK" opcode="110401"></opcodes>
				<opcodes xmlname="defaultPIN" opcode="110601"></opcodes>
				<opcodes xmlname="defaultPUK" opcode="110701"></opcodes>
				<opcodes xmlname="defaultAdminPIN" opcode="110801"></opcodes>
		</cardinfo>
		<cardinfo name="oberthurv8.1" cardid="3033333130">
				<opcodes xmlname="defaultCMK" opcode="110401"></opcodes>
				<opcodes xmlname="defaultPIN" opcode="110601"></opcodes>
				<opcodes xmlname="defaultPUK" opcode="110701"></opcodes>
				<opcodes xmlname="defaultAdminPIN" opcode="110801"></opcodes>
		</cardinfo>
		<cardinfo name="yubikey" cardid="3035313032">
				<opcodes xmlname="defaultCMK" opcode="120400"></opcodes>
				<opcodes xmlname="defaultCMKAlgorid" opcode="140400"></opcodes>
				<opcodes xmlname="divCMKAlgorid" opcode="130400"></opcodes>
				<opcodes xmlname="defaultPIN" opcode="120600"></opcodes>
				<opcodes xmlname="defaultPUK" opcode="120700"></opcodes>
				<opcodes xmlname="divPUK" opcode="110701"></opcodes>
				<opcodes xmlname="divCMK" opcode="110401"></opcodes>
		</cardinfo>
		<cardinfo name="oberthurv8.2" cardid="3033333133">
				<opcodes xmlname="defaultCMK" opcode="110401"></opcodes>
				<opcodes xmlname="defaultPIN" opcode="110601"></opcodes>
				<opcodes xmlname="defaultPUK" opcode="110701"></opcodes>
				<opcodes xmlname="defaultAdminPIN" opcode="110801"></opcodes>
		</cardinfo>

</configcard>

CARDCONFIG;

$xstype = array(
"3035313031" => "yubikey",
);



?>
