<?PHP
// $Id: config-capture.php 3449 2019-03-12 20:23:12Z jgutierrez $
// Service configuration file
//    xsvc-capture.xas?id=useracid
// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in the writedata service. Here for compatibility only
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : MULTI
//  0x02 : 
//  0x04 : Date formatting required from/to LDAP format to MM-DD-YYYY format.
//  0x08 : Nosave. Data is not saved to the database.
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
//  0x100:
//	0x200: The element is to be encrypted/decrypted for database storage

require_once("../../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "captureresult";
$_service_version = "1.0";

$wflow = "dac";

$_db_elements = array (
//was line407
"entity:sysid=logs:objectlog:xsystem|auth_objectlog|PIV Auth Object Log|txt:txt|0x01",
"entity:gcoid=clearance:xblk:00310b:gco|sys_objectlog|Deprecated|txt:txt|0x00",
"entity:gcoid=token,procid=token,ounit=".$wflow.":xblk:0020c6:gco|cardtop|Card Topology|txt:txt|0x00",
"entity:procid=token,ounit=".$wflow.":objectlog:process|token_objectlog|Token Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|token_objectlog|System Object Log|txt:txt|0x01",
"token:status:credential|token_status|Token Status|txt:txt|0x00",
"entity:bioid=portrait:jpgpic:biometric|portrait|Portrait|b64:bin|0x00",
"entity:bioid=R_Thumb:wsqdata:biometric|LS_R_Thumb_WSQ|Live Scan Right Thumb WSQ|b64:bin|0x00",
"entity:bioid=R_Thumb:desc:biometric|LS_R_Thumb_DESC|Live Scan Right Thumb Desc|txt:txt|0x00",
"entity:bioid=R_Thumb:nfiq:biometric|LS_R_Thumb_NFIQ|Live Scan Right Thumb NFIQ|txt:txt|0x00",
"entity:bioid=R_Thumb:rem:biometric|LS_R_Thumb_AMP|Live Scan Right Thumb AMP|txt:txt|0x00",
"entity:bioid=R_Index:wsqdata:biometric|LS_R_Index_WSQ|Live Scan Right Index WSQ|b64:bin|0x00",
"entity:bioid=R_Index:desc:biometric|LS_R_Index_DESC|Live Scan Right Index Desc|txt:txt|0x00",
"entity:bioid=R_Index:nfiq:biometric|LS_R_Index_NFIQ|Live Scan Right Index NFIQ|txt:txt|0x00",
"entity:bioid=R_Index:rem:biometric|LS_R_Index_AMP|Live Scan Right Index AMP|txt:txt|0x00",
"entity:bioid=ANSI378_Template_R_Index,bioid=R_Index:xblk:biometric|LS_R_Index_ANSI378|Live Scan Right Index ANSI378 Template|b64:bin|0x00",
"entity:bioid=R_Middle:wsqdata:biometric|LS_R_Middle_WSQ|Live Scan Right Middle WSQ|b64:bin|0x00",
"entity:bioid=R_Middle:desc:biometric|LS_R_Middle_DESC|Live Scan Right Middle Desc|txt:txt|0x00",
"entity:bioid=R_Middle:nfiq:biometric|LS_R_Middle_NFIQ|Live Scan Right Middle NFIQ|txt:txt|0x00",
"entity:bioid=R_Middle:rem:biometric|LS_R_Middle_AMP|Live Scan Right Middle AMP|txt:txt|0x00",
"entity:bioid=R_Ring:wsqdata:biometric|LS_R_Ring_WSQ|Live Scan Right Ring WSQ|b64:bin|0x00",
"entity:bioid=R_Ring:desc:biometric|LS_R_Ring_DESC|Live Scan Right Ring Desc|txt:txt|0x00",
"entity:bioid=R_Ring:nfiq:biometric|LS_R_Ring_NFIQ|Live Scan Right Ring NFIQ|txt:txt|0x00",
"entity:bioid=R_Ring:rem:biometric|LS_R_Ring_AMP|Live Scan Right Ring AMP|txt:txt|0x00",
"entity:bioid=R_Little:wsqdata:biometric|LS_R_Little_WSQ|Live Scan Right Little WSQ|b64:bin|0x00",
"entity:bioid=R_Little:desc:biometric|LS_R_Little_DESC|Live Scan Right Little Desc|txt:txt|0x00",
"entity:bioid=R_Little:nfiq:biometric|LS_R_Little_NFIQ|Live Scan Right Little NFIQ|txt:txt|0x00",
"entity:bioid=R_Little:rem:biometric|LS_R_Little_AMP|Live Scan Right Little AMP|txt:txt|0x00",
"entity:bioid=R_Slap_LS:wsqdata:biometric|LS_R_SLAP_WSQ|Live Scan Right Slap WSQ|b64:bin|0x00",
"entity:bioid=R_Slap_LS:desc:biometric|LS_R_SLAP_DESC|Live Scan Right Slap Desc|txt:txt|0x00",
"entity:bioid=R_Slap_LS:nfiq:biometric|LS_R_SLAP_NFIQ|Live Scan Right Slap NFIQ|txt:txt|0x00",
"entity:bioid=RT_Plain_LS:wsqdata:biometric|LS_RT_PLAIN_WSQ|Live Scan Right Thumb Plain WSQ|b64:bin|0x00",
"entity:bioid=RT_Plain_LS:desc:biometric|LS_RT_PLAIN_DESC|Live Scan Right Thumb Plain Desc|txt:txt|0x00",
"entity:bioid=RT_Plain_LS:nfiq:biometric|LS_RT_PLAIN_NFIQ|Live Scan Right Thumb Plain NFIQ|txt:txt|0x00",
"entity:bioid=L_Thumb:wsqdata:biometric|LS_L_Thumb_WSQ|Live Scan Left Thumb WSQ|b64:bin|0x00",
"entity:bioid=L_Thumb:desc:biometric|LS_L_Thumb_DESC|Live Scan Left Thumb Desc|txt:txt|0x00",
"entity:bioid=L_Thumb:nfiq:biometric|LS_L_Thumb_NFIQ|Live Scan Left Thumb NFIQ|txt:txt|0x00",
"entity:bioid=L_Thumb:rem:biometric|LS_L_Thumb_AMP|Live Scan Left Thumb AMP|txt:txt|0x00",
"entity:bioid=L_Index:wsqdata:biometric|LS_L_Index_WSQ|Live Scan Left Index WSQ|b64:bin|0x00",
"entity:bioid=L_Index:desc:biometric|LS_L_Index_DESC|Live Scan Left Index Desc|txt:txt|0x00",
"entity:bioid=L_Index:nfiq:biometric|LS_L_Index_NFIQ|Live Scan Left Index NFIQ|txt:txt|0x00",
"entity:bioid=L_Index:rem:biometric|LS_L_Index_AMP|Live Scan Left Index AMP|txt:txt|0x00",
"entity:bioid=ANSI378_Template_L_Index,bioid=L_Index:xblk:biometric|LS_L_Index_ANSI378|Live Scan Left Index ANSI378 Template|b64:bin|0x00",
"entity:bioid=L_Middle:wsqdata:biometric|LS_L_Middle_WSQ|Live Scan Left Middle WSQ|b64:bin|0x00",
"entity:bioid=L_Middle:desc:biometric|LS_L_Middle_DESC|Live Scan Left Middle Desc|txt:txt|0x00",
"entity:bioid=L_Middle:nfiq:biometric|LS_L_Middle_NFIQ|Live Scan Left Middle NFIQ|txt:txt|0x00",
"entity:bioid=L_Middle:rem:biometric|LS_L_Middle_AMP|Live Scan Left Middle AMP|txt:txt|0x00",
"entity:bioid=L_Ring:wsqdata:biometric|LS_L_Ring_WSQ|Live Scan Left Ring WSQ|b64:bin|0x00",
"entity:bioid=L_Ring:desc:biometric|LS_L_Ring_DESC|Live Scan Left Ring Desc|txt:txt|0x00",
"entity:bioid=L_Ring:nfiq:biometric|LS_L_Ring_NFIQ|Live Scan Left Ring NFIQ|txt:txt|0x00",
"entity:bioid=L_Ring:rem:biometric|LS_L_Ring_AMP|Live Scan Left Ring AMP|txt:txt|0x00",
"entity:bioid=L_Little:wsqdata:biometric|LS_L_Little_WSQ|Live Scan Left Little WSQ|b64:bin|0x00",
"entity:bioid=L_Little:desc:biometric|LS_L_Little_DESC|Live Scan Left Little Desc|txt:txt|0x00",
"entity:bioid=L_Little:nfiq:biometric|LS_L_Little_NFIQ|Live Scan Left Little NFIQ|txt:txt|0x00",
"entity:bioid=L_Little:rem:biometric|LS_L_Little_AMP|Live Scan Left Little AMP|txt:txt|0x00",
"entity:bioid=L_Slap_LS:wsqdata:biometric|LS_L_SLAP_WSQ|Live Scan Left Slap WSQ|b64:bin|0x00",
"entity:bioid=L_Slap_LS:desc:biometric|LS_L_SLAP_DESC|Live Scan Left Slap Desc|txt:txt|0x00",
"entity:bioid=L_Slap_LS:nfiq:biometric|LS_L_SLAP_NFIQ|Live Scan Left Slap NFIQ|txt:txt|0x00",
"entity:bioid=LT_Plain_LS:wsqdata:biometric|LS_LT_PLAIN_WSQ|Live Scan Left Thumb Plain WSQ|b64:bin|0x00",
"entity:bioid=LT_Plain_LS:desc:biometric|LS_LT_PLAIN_DESC|Live Scan Left Thumb Plain Desc|txt:txt|0x00",
"entity:bioid=LT_Plain_LS:nfiq:biometric|LS_LT_PLAIN_NFIQ|Live Scan Left Thumb Plain NFIQ|txt:txt|0x00",
"entity:bioid=BT_Plain_LS:wsqdata:biometric|LS_BT_PLAIN_WSQ|Live Scan Both Thumbs Plain WSQ|b64:bin|0x00",
"entity:bioid=BT_Plain_LS:desc:biometric|LS_BT_PLAIN_DESC|Live Scan Both Thumbs Plain Desc|txt:txt|0x00",
"entity:bioid=BT_Plain_LS:nfiq:biometric|LS_BT_PLAIN_NFIQ|Live Scan Both Thumbs Plain NFIQ|txt:txt|0x00",
"entity:bioid=R_Thumb_CS:wsqdata:biometric|CS_R_Thumb_WSQ|Card Scan Right Thumb WSQ|b64:bin|0x00",
"entity:bioid=R_Thumb_CS:desc:biometric|CS_R_Thumb_DESC|Card Scan Right Thumb Desc|txt:txt|0x00",
"entity:bioid=R_Thumb_CS:nfiq:biometric|CS_R_Thumb_NFIQ|Card Scan Right Thumb NFIQ|txt:txt|0x00",
"entity:bioid=R_Thumb_CS:rem:biometric|CS_R_Thumb_AMP|Card Scan Right Thumb AMP|txt:txt|0x00",
"entity:bioid=R_Index_CS:wsqdata:biometric|CS_R_Index_WSQ|Card Scan Right Index WSQ|b64:bin|0x00",
"entity:bioid=R_Index_CS:desc:biometric|CS_R_Index_DESC|Card Scan Right Index Desc|txt:txt|0x00",
"entity:bioid=R_Index_CS:nfiq:biometric|CS_R_Index_NFIQ|Card Scan Right Index NFIQ|txt:txt|0x00",
"entity:bioid=R_Index_CS:rem:biometric|CS_R_Index_AMP|Card Scan Right Index AMP|txt:txt|0x00",
"entity:bioid=ANSI378_Template_R_Index_CS,bioid=R_Index_CS:xblk:biometric|CS_R_Index_ANSI378|Card Scan Right Index ANSI378 Template|b64:bin|0x00",
"entity:bioid=R_Middle_CS:wsqdata:biometric|CS_R_Middle_WSQ|Card Scan Right Middle WSQ|b64:bin|0x00",
"entity:bioid=R_Middle_CS:desc:biometric|CS_R_Middle_DESC|Card Scan Right Middle Desc|txt:txt|0x00",
"entity:bioid=R_Middle_CS:nfiq:biometric|CS_R_Middle_NFIQ|Card Scan Right Middle NFIQ|txt:txt|0x00",
"entity:bioid=R_Middle_CS:rem:biometric|CS_R_Middle_AMP|Card Scan Right Middle AMP|txt:txt|0x00",
"entity:bioid=R_Ring_CS:wsqdata:biometric|CS_R_Ring_WSQ|Card Scan Right Ring WSQ|b64:bin|0x00",
"entity:bioid=R_Ring_CS:desc:biometric|CS_R_Ring_DESC|Card Scan Right Ring Desc|txt:txt|0x00",
"entity:bioid=R_Ring_CS:nfiq:biometric|CS_R_Ring_NFIQ|Card Scan Right Ring NFIQ|txt:txt|0x00",
"entity:bioid=R_Ring_CS:rem:biometric|CS_R_Ring_AMP|Card Scan Right Ring AMP|txt:txt|0x00",
"entity:bioid=R_Little_CS:wsqdata:biometric|CS_R_Little_WSQ|Card Scan Right Little WSQ|b64:bin|0x00",
"entity:bioid=R_Little_CS:desc:biometric|CS_R_Little_DESC|Card Scan Right Little Desc|txt:txt|0x00",
"entity:bioid=R_Little_CS:nfiq:biometric|CS_R_Little_NFIQ|Card Scan Right Little NFIQ|txt:txt|0x00",
"entity:bioid=R_Little_CS:rem:biometric|CS_R_Little_AMP|Card Scan Right Little AMP|txt:txt|0x00",
"entity:bioid=R_Slap_CS:wsqdata:biometric|CS_R_SLAP_WSQ|Card Scan Right Slap WSQ|b64:bin|0x00",
"entity:bioid=R_Slap_CS:desc:biometric|CS_R_SLAP_DESC|Card Scan Right Slap Desc|txt:txt|0x00",
"entity:bioid=R_Slap_CS:nfiq:biometric|CS_R_SLAP_NFIQ|Card Scan Right Slap NFIQ|txt:txt|0x00",
"entity:bioid=RT_Plain_CS:wsqdata:biometric|CS_RT_PLAIN_WSQ|Card Scan Right Thumb Plain WSQ|b64:bin|0x00",
"entity:bioid=RT_Plain_CS:desc:biometric|CS_RT_PLAIN_DESC|Card Scan Right Thumb Plain Desc|txt:txt|0x00",
"entity:bioid=RT_Plain_CS:nfiq:biometric|CS_RT_PLAIN_NFIQ|Card Scan Right Thumb Plain NFIQ|txt:txt|0x00",
"entity:bioid=L_Thumb_CS:wsqdata:biometric|CS_L_Thumb_WSQ|Card Scan Left Thumb WSQ|b64:bin|0x00",
"entity:bioid=L_Thumb_CS:desc:biometric|CS_L_Thumb_DESC|Card Scan Left Thumb Desc|txt:txt|0x00",
"entity:bioid=L_Thumb_CS:nfiq:biometric|CS_L_Thumb_NFIQ|Card Scan Left Thumb NFIQ|txt:txt|0x00",
"entity:bioid=L_Thumb_CS:rem:biometric|CS_L_Thumb_AMP|Card Scan Left Thumb AMP|txt:txt|0x00",
"entity:bioid=L_Index_CS:wsqdata:biometric|CS_L_Index_WSQ|Card Scan Left Index WSQ|b64:bin|0x00",
"entity:bioid=L_Index_CS:desc:biometric|CS_L_Index_DESC|Card Scan Left Index Desc|txt:txt|0x00",
"entity:bioid=L_Index_CS:nfiq:biometric|CS_L_Index_NFIQ|Card Scan Left Index NFIQ|txt:txt|0x00",
"entity:bioid=L_Index_CS:rem:biometric|CS_L_Index_AMP|Card Scan Left Index AMP|txt:txt|0x00",
"entity:bioid=ANSI378_Template_L_Index_CS,bioid=L_Index_CS:xblk:biometric|CS_L_Index_ANSI378|Card Scan Left Index ANSI378 Template|b64:bin|0x00",
"entity:bioid=L_Middle_CS:wsqdata:biometric|CS_L_Middle_WSQ|Card Scan Left Middle WSQ|b64:bin|0x00",
"entity:bioid=L_Middle_CS:desc:biometric|CS_L_Middle_DESC|Card Scan Left Middle Desc|txt:txt|0x00",
"entity:bioid=L_Middle_CS:nfiq:biometric|CS_L_Middle_NFIQ|Card Scan Left Middle NFIQ|txt:txt|0x00",
"entity:bioid=L_Middle_CS:rem:biometric|CS_L_Middle_AMP|Card Scan Left Middle AMP|txt:txt|0x00",
"entity:bioid=L_Ring_CS:wsqdata:biometric|CS_L_Ring_WSQ|Card Scan Left Ring WSQ|b64:bin|0x00",
"entity:bioid=L_Ring_CS:desc:biometric|CS_L_Ring_DESC|Card Scan Left Ring Desc|txt:txt|0x00",
"entity:bioid=L_Ring_CS:nfiq:biometric|CS_L_Ring_NFIQ|Card Scan Left Ring NFIQ|txt:txt|0x00",
"entity:bioid=L_Ring_CS:rem:biometric|CS_L_Ring_AMP|Card Scan Left Ring AMP|txt:txt|0x00",
"entity:bioid=L_Little_CS:wsqdata:biometric|CS_L_Little_WSQ|Card Scan Left Little WSQ|b64:bin|0x00",
"entity:bioid=L_Little_CS:desc:biometric|CS_L_Little_DESC|Card Scan Left Little Desc|txt:txt|0x00",
"entity:bioid=L_Little_CS:nfiq:biometric|CS_L_Little_NFIQ|Card Scan Left Little NFIQ|txt:txt|0x00",
"entity:bioid=L_Little_CS:rem:biometric|CS_L_Little_AMP|Card Scan Left Little AMP|txt:txt|0x00",
"entity:bioid=L_Slap_CS:wsqdata:biometric|CS_L_SLAP_WSQ|Card Scan Left Slap WSQ|b64:bin|0x00",
"entity:bioid=L_Slap_CS:desc:biometric|CS_L_SLAP_DESC|Card Scan Left Slap Desc|txt:txt|0x00",
"entity:bioid=L_Slap_CS:nfiq:biometric|CS_L_SLAP_NFIQ|Card Scan Left Slap NFIQ|txt:txt|0x00",
"entity:bioid=LT_Plain_CS:wsqdata:biometric|CS_LT_PLAIN_WSQ|Card Scan Left Thumb Plain WSQ|b64:bin|0x00",
"entity:bioid=LT_Plain_CS:desc:biometric|CS_LT_PLAIN_DESC|Card Scan Left Thumb Plain Desc|txt:txt|0x00",
"entity:bioid=PIV_Primary:xblk:biometric|PIV_Primary_Template|PIV Primary Template|b64:bin|0x00",
"entity:bioid=PIV_Primary:desc:biometric|PIV_Primary_DESC|PIV Primary Template Desc|txt:txt|0x00",
"entity:bioid=PIV_Primary:nfiq:biometric|PIV_Primary_NFIQ|PIV Primary Template NFIQ|txt:txt|0x00",
"entity:bioid=PIV_Primary:rem:biometric|PIV_Primary_Finger_Number|PIV Primary Template Finger Number|txt:txt|0x00",
"entity:bioid=PIV_Secondary:xblk:biometric|PIV_Secondary_Template|PIV Secondary Template|b64:bin|0x00",
"entity:bioid=PIV_Secondary:desc:biometric|PIV_Secondary_DESC|PIV Primary Template Desc|txt:txt|0x00",
"entity:bioid=PIV_Secondary:nfiq:biometric|PIV_Secondary_NFIQ|PIV Secondary Template NFIQ|txt:txt|0x00",
"entity:bioid=PIV_Secondary:rem:biometric|PIV_Secondary_Finger_Number|PIV Secondary Template Finger Number|txt:txt|0x00",
"entity:docid=passport:desc:xdocument|passport_device|US Passport Capture Device|txt:txt|0x00",
"entity:docid=passport:authval:xdocument|passport_id|US Passport ID|txt:txt|0x00",
"entity:docid=passport:jpgpic:xdocument|passport_visible|US Passport Visible Image|b64:bin|0x00",
"entity:docid=passport:issdate:xdocument|passport_issdate|US Passport Issue Date|txt:txt|0x04",
"entity:docid=passport:expdate:xdocument|passport_expdate|US Passport Expiration Date|txt:txt|0x04",
"entity:docid=passport:xblk:xdocument|passport_info|US Passport Information|txt:txt|0x00",
"entity:docid=cizenship:desc:xdocument|cizenship_device|Certificate of US Citizenship Capture Device|txt:txt|0x00",
"entity:docid=cizenship:authval:xdocument|cizenship_id|Certificate of US Citizenship ID|txt:txt|0x00",
"entity:docid=cizenship:jpgpic:xdocument|cizenship_visible|Certificate of US Citizenship Visible Image|b64:bin|0x00",
"entity:docid=cizenship:issdate:xdocument|cizenship_issdate|Certificate of US Citizenship Issue Date|txt:txt|0x04",
"entity:docid=cizenship:expdate:xdocument|cizenship_expdate|Certificate of US Citizenship Expiration Date|txt:txt|0x04",
"entity:docid=cizenship:xblk:xdocument|cizenship_info|Certificate of US Citizenship Information|txt:txt|0x00",
"entity:docid=naturalization:desc:xdocument|naturalization_device|Certificate of Naturalization Capture Device|txt:txt|0x00",
"entity:docid=naturalization:authval:xdocument|naturalization_id|Certificate of Naturalization ID|txt:txt|0x00",
"entity:docid=naturalization:jpgpic:xdocument|naturalization_visible|Certificate of Naturalization Visible Image|b64:bin|0x00",
"entity:docid=naturalization:issdate:xdocument|naturalization_issdate|Certificate of Naturalization Issue Date|txt:txt|0x04",
"entity:docid=naturalization:expdate:xdocument|naturalization_expdate|Certificate of Naturalization Expiration Date|txt:txt|0x04",
"entity:docid=naturalization:xblk:xdocument|naturalization_info|Certificate of Naturalization Information|txt:txt|0x00",
"entity:docid=foreignpassport:desc:xdocument|foreignpassport_device|Foreign Passport Capture Device|txt:txt|0x00",
"entity:docid=foreignpassport:authval:xdocument|foreignpassport_id|Foreign Passport ID|txt:txt|0x00",
"entity:docid=foreignpassport:jpgpic:xdocument|foreignpassport_visible|Foreign Passport Visible Image|b64:bin|0x00",
"entity:docid=foreignpassport:issdate:xdocument|foreignpassport_issdate|Foreign Passport Issue Date|txt:txt|0x04",
"entity:docid=foreignpassport:expdate:xdocument|foreignpassport_expdate|Foreign Passport Expiration Date|txt:txt|0x04",
"entity:docid=foreignpassport:xblk:xdocument|foreignpassport_info|Foreign Passport Information|txt:txt|0x00",
"entity:docid=resident:desc:xdocument|resident_device|Permanent Resident or Alien Registration Card Capture Device|txt:txt|0x00",
"entity:docid=resident:authval:xdocument|resident_id|Permanent Resident or Alien Registration Card ID|txt:txt|0x00",
"entity:docid=resident:jpgpic:xdocument|resident_visible|Permanent Resident or Alien Registration Card Visible Image|b64:bin|0x00",
"entity:docid=resident:issdate:xdocument|resident_issdate|Permanent Resident or Alien Registration Card Issue Date|txt:txt|0x04",
"entity:docid=resident:expdate:xdocument|resident_expdate|Permanent Resident or Alien Registration Card Expiration Date|txt:txt|0x04",
"entity:docid=resident:xblk:xdocument|resident_info|Permanent Resident or Alien Registration Card Information|txt:txt|0x00",
"entity:docid=tempresident:desc:xdocument|tempresident_device|Temporary Resident Card Capture Device|txt:txt|0x00",
"entity:docid=tempresident:authval:xdocument|tempresident_id|Temporary Resident Card ID|txt:txt|0x00",
"entity:docid=tempresident:jpgpic:xdocument|tempresident_visible|Temporary Resident Card Visible Image|b64:bin|0x00",
"entity:docid=tempresident:issdate:xdocument|tempresident_issdate|Temporary Resident Card Issue Date|txt:txt|0x04",
"entity:docid=tempresident:expdate:xdocument|tempresident_expdate|Temporary Resident Card Expiration Date|txt:txt|0x04",
"entity:docid=tempresident:xblk:xdocument|tempresident_info|Temporary Resident Card Information|txt:txt|0x00",
"entity:docid=employment:desc:xdocument|employment_device|Employment Authorization Card Capture Device|txt:txt|0x00",
"entity:docid=employment:authval:xdocument|employment_id|Employment Authorization Card ID|txt:txt|0x00",
"entity:docid=employment:jpgpic:xdocument|employment_visible|Employment Authorization Card Visible Image|b64:bin|0x00",
"entity:docid=employment:issdate:xdocument|employment_issdate|Employment Authorization Card Issue Date|txt:txt|0x04",
"entity:docid=employment:expdate:xdocument|employment_expdate|Employment Authorization Card Expiration Date|txt:txt|0x04",
"entity:docid=employment:xblk:xdocument|employment_info|Employment Authorization Card Information|txt:txt|0x00",
"entity:docid=reentry:desc:xdocument|reentry_device|Reentry Permit Capture Device|txt:txt|0x00",
"entity:docid=reentry:authval:xdocument|reentry_id|Reentry Permit ID|txt:txt|0x00",
"entity:docid=reentry:jpgpic:xdocument|reentry_visible|Reentry Permit Visible Image|b64:bin|0x00",
"entity:docid=reentry:issdate:xdocument|reentry_issdate|Reentry Permit Issue Date|txt:txt|0x04",
"entity:docid=reentry:expdate:xdocument|reentry_expdate|Reentry Permit Expiration Date|txt:txt|0x04",
"entity:docid=reentry:xblk:xdocument|reentry_info|Reentry Permit Information|txt:txt|0x00",
"entity:docid=refugee:desc:xdocument|refugee_device|Refugee Travel Document Capture Device|txt:txt|0x00",
"entity:docid=refugee:authval:xdocument|refugee_id|Refugee Travel Document ID|txt:txt|0x00",
"entity:docid=refugee:jpgpic:xdocument|refugee_visible|Refugee Travel Document Visible Image|b64:bin|0x00",
"entity:docid=refugee:issdate:xdocument|refugee_issdate|Refugee Travel Document Issue Date|txt:txt|0x04",
"entity:docid=refugee:expdate:xdocument|refugee_expdate|Refugee Travel Document Expiration Date|txt:txt|0x04",
"entity:docid=refugee:xblk:xdocument|refugee_info|Refugee Travel Document Information|txt:txt|0x00",
"entity:docid=usaccessemplyment:desc:xdocument|usaccessemplyment_device|Employment Authorization Document Capture Device|txt:txt|0x00",
"entity:docid=usaccessemplyment:authval:xdocument|usaccessemplyment_id|Employment Authorization Document ID|txt:txt|0x00",
"entity:docid=usaccessemplyment:jpgpic:xdocument|usaccessemplyment_visible|Employment Authorization Document Visible Image|b64:bin|0x00",
"entity:docid=usaccessemplyment:issdate:xdocument|usaccessemplyment_issdate|Employment Authorization Document Issue Date|txt:txt|0x04",
"entity:docid=usaccessemplyment:expdate:xdocument|usaccessemplyment_expdate|Employment Authorization Document Expiration Date|txt:txt|0x04",
"entity:docid=usaccessemplyment:xblk:xdocument|usaccessemplyment_info|Employment Authorization Document Information|txt:txt|0x00",
"entity:docid=driverslic:desc:xdocument|driverslic_device|Drivers License Capture Device|txt:txt|0x00",
"entity:docid=driverslic:authval:xdocument|driverslic_id|Drivers License ID|txt:txt|0x00",
"entity:docid=driverslic:jpgpic:xdocument|driverslic_visible|Drivers License Visible Image|b64:bin|0x00",
"entity:docid=driverslic:issdate:xdocument|driverslic_issdate|Drivers License Issue Date|txt:txt|0x04",
"entity:docid=driverslic:expdate:xdocument|driverslic_expdate|Drivers License Expiration Date|txt:txt|0x04",
"entity:docid=driverslic:xblk:xdocument|driverslic_info|Drivers License Information|txt:txt|0x00",
"entity:docid=govid:desc:xdocument|govid_device|Other Federal, State or Local ID Card Capture Device|txt:txt|0x00",
"entity:docid=govid:authval:xdocument|govid_id|Other Federal, State or Local ID Card ID|txt:txt|0x00",
"entity:docid=govid:jpgpic:xdocument|govid_visible|Other Federal, State or Local ID Card Visible Image|b64:bin|0x00",
"entity:docid=govid:issdate:xdocument|govid_issdate|Other Federal, State or Local ID Card Issue Date|txt:txt|0x04",
"entity:docid=govid:expdate:xdocument|govid_expdate|Other Federal, State or Local ID Card Expiration Date|txt:txt|0x04",
"entity:docid=govid:xblk:xdocument|govid_info|Other Federal, State or Local ID Card Information|txt:txt|0x00",
"entity:docid=schoolid:desc:xdocument|schoolid_device|School ID Card Capture Device|txt:txt|0x00",
"entity:docid=schoolid:authval:xdocument|schoolid_id|School ID Card ID|txt:txt|0x00",
"entity:docid=schoolid:jpgpic:xdocument|schoolid_visible|School ID Card Visible Image|b64:bin|0x00",
"entity:docid=schoolid:issdate:xdocument|schoolid_issdate|School ID Card Issue Date|txt:txt|0x04",
"entity:docid=schoolid:expdate:xdocument|schoolid_expdate|School ID Card Expiration Date|txt:txt|0x04",
"entity:docid=schoolid:xblk:xdocument|schoolid_info|School ID Card Information|txt:txt|0x00",
"entity:docid=voters:desc:xdocument|voters_device|Voters Registration Card Capture Device|txt:txt|0x00",
"entity:docid=voters:authval:xdocument|voters_id|Voters Registration Card ID|txt:txt|0x00",
"entity:docid=voters:jpgpic:xdocument|voters_visible|Voters Registration Card Visible Image|b64:bin|0x00",
"entity:docid=voters:issdate:xdocument|voters_issdate|Voters Registration Card Issue Date|txt:txt|0x04",
"entity:docid=voters:expdate:xdocument|voters_expdate|Voters Registration Card Expiration Date|txt:txt|0x04",
"entity:docid=voters:xblk:xdocument|voters_info|Voters Registration Card Information|txt:txt|0x00",
"entity:docid=usmilid:desc:xdocument|usmilid_device|US Military Card Capture Device|txt:txt|0x00",
"entity:docid=usmilid:authval:xdocument|usmilid_id|US Military Card ID|txt:txt|0x00",
"entity:docid=usmilid:jpgpic:xdocument|usmilid_visible|US Military Card Visible Image|b64:bin|0x00",
"entity:docid=usmilid:issdate:xdocument|usmilid_issdate|US Military Card Issue Date|txt:txt|0x04",
"entity:docid=usmilid:expdate:xdocument|usmilid_expdate|US Military Card Expiration Date|txt:txt|0x04",
"entity:docid=usmilid:xblk:xdocument|usmilid_info|US Military Card Information|txt:txt|0x00",
"entity:docid=usmildependant:desc:xdocument|usmildependant_device|US Miltary Dependant ID Card Capture Device|txt:txt|0x00",
"entity:docid=usmildependant:authval:xdocument|usmildependant_id|US Miltary Dependant ID Card ID|txt:txt|0x00",
"entity:docid=usmildependant:jpgpic:xdocument|usmildependant_visible|US Miltary Dependant ID Card Visible Image|b64:bin|0x00",
"entity:docid=usmildependant:issdate:xdocument|usmildependant_issdate|US Miltary Dependant ID Card Issue Date|txt:txt|0x04",
"entity:docid=usmildependant:expdate:xdocument|usmildependant_expdate|US Miltary Dependant ID Card Expiration Date|txt:txt|0x04",
"entity:docid=usmildependant:xblk:xdocument|usmildependant_info|US Miltary Dependant ID Card Information|txt:txt|0x00",
"entity:docid=uscgmac:desc:xdocument|uscgmac_device|US Coast Guard Mariner Card Capture Device|txt:txt|0x00",
"entity:docid=uscgmac:authval:xdocument|uscgmac_id|US Coast Guard Mariner Card ID|txt:txt|0x00",
"entity:docid=uscgmac:jpgpic:xdocument|uscgmac_visible|US Coast Guard Mariner Card Visible Image|b64:bin|0x00",
"entity:docid=uscgmac:issdate:xdocument|uscgmac_issdate|US Coast Guard Mariner Card Issue Date|txt:txt|0x04",
"entity:docid=uscgmac:expdate:xdocument|uscgmac_expdate|US Coast Guard Mariner Card Expiration Date|txt:txt|0x04",
"entity:docid=uscgmac:xblk:xdocument|uscgmac_info|US Coast Guard Mariner Card Information|txt:txt|0x00",
"entity:docid=nativeamerican:desc:xdocument|nativeamerican_device|Native American Tribal Document Capture Device|txt:txt|0x00",
"entity:docid=nativeamerican:authval:xdocument|nativeamerican_id|Native American Tribal Document ID|txt:txt|0x00",
"entity:docid=nativeamerican:jpgpic:xdocument|nativeamerican_visible|Native American Tribal Document Visible Image|b64:bin|0x00",
"entity:docid=nativeamerican:issdate:xdocument|nativeamerican_issdate|Native American Tribal Document Issue Date|txt:txt|0x04",
"entity:docid=nativeamerican:expdate:xdocument|nativeamerican_expdate|Native American Tribal Document Expiration Date|txt:txt|0x04",
"entity:docid=nativeamerican:xblk:xdocument|nativeamerican_info|Native American Tribal Document Information|txt:txt|0x00",
"entity:docid=schoolrecord:desc:xdocument|schoolrecord_device|School Record or Report Card Capture Device|txt:txt|0x00",
"entity:docid=schoolrecord:authval:xdocument|schoolrecord_id|School Record or Report Card ID|txt:txt|0x00",
"entity:docid=schoolrecord:jpgpic:xdocument|schoolrecord_visible|School Record or Report Card Visible Image|b64:bin|0x00",
"entity:docid=schoolrecord:issdate:xdocument|schoolrecord_issdate|School Record or Report Card Issue Date|txt:txt|0x04",
"entity:docid=schoolrecord:expdate:xdocument|schoolrecord_expdate|School Record or Report Card Expiration Date|txt:txt|0x04",
"entity:docid=schoolrecord:xblk:xdocument|schoolrecord_info|School Record or Report Card Information|txt:txt|0x00",
"entity:docid=medrecord:desc:xdocument|medrecord_device|Medical Record Capture Device|txt:txt|0x00",
"entity:docid=medrecord:authval:xdocument|medrecord_id|Medical Record ID|txt:txt|0x00",
"entity:docid=medrecord:jpgpic:xdocument|medrecord_visible|Medical Record Visible Image|b64:bin|0x00",
"entity:docid=medrecord:issdate:xdocument|medrecord_issdate|Medical Record Issue Date|txt:txt|0x04",
"entity:docid=medrecord:expdate:xdocument|medrecord_expdate|Medical Record Expiration Date|txt:txt|0x04",
"entity:docid=medrecord:xblk:xdocument|medrecord_info|Medical Record Information|txt:txt|0x00",
"entity:docid=nurseryrecord:desc:xdocument|nurseryrecord_device|Nursery School Record Capture Device|txt:txt|0x00",
"entity:docid=nurseryrecord:authval:xdocument|nurseryrecord_id|Nursery School Record ID|txt:txt|0x00",
"entity:docid=nurseryrecord:jpgpic:xdocument|nurseryrecord_visible|Nursery School Record Visible Image|b64:bin|0x00",
"entity:docid=nurseryrecord:issdate:xdocument|nurseryrecord_issdate|Nursery School Record Issue Date|txt:txt|0x04",
"entity:docid=nurseryrecord:expdate:xdocument|nurseryrecord_expdate|Nursery School Record Expiration Date|txt:txt|0x04",
"entity:docid=nurseryrecord:xblk:xdocument|nurseryrecord_info|Nursery School Record Information|txt:txt|0x00",
"entity:docid=ussocsec:desc:xdocument|ussocsec_device|US Social Security Card Capture Device|txt:txt|0x00",
"entity:docid=ussocsec:authval:xdocument|ussocsec_id|US Social Security Card ID|txt:txt|0x00",
"entity:docid=ussocsec:jpgpic:xdocument|ussocsec_visible|US Social Security Card Visible Image|b64:bin|0x00",
"entity:docid=ussocsec:issdate:xdocument|ussocsec_issdate|US Social Security Card Issue Date|txt:txt|0x04",
"entity:docid=ussocsec:expdate:xdocument|ussocsec_expdate|US Social Security Card Expiration Date|txt:txt|0x04",
"entity:docid=ussocsec:xblk:xdocument|ussocsec_info|US Social Security Card Information|txt:txt|0x00",
"entity:docid=birthcertdos:desc:xdocument|birthcertdos_device|DoS or Abroad Birth Certificate Capture Device|txt:txt|0x00",
"entity:docid=birthcertdos:authval:xdocument|birthcertdos_id|DoS or Abroad Birth Certificate ID|txt:txt|0x00",
"entity:docid=birthcertdos:jpgpic:xdocument|birthcertdos_visible|DoS or Abroad Birth Certificate Visible Image|b64:bin|0x00",
"entity:docid=birthcertdos:issdate:xdocument|birthcertdos_issdate|DoS or Abroad Birth Certificate Issue Date|txt:txt|0x04",
"entity:docid=birthcertdos:expdate:xdocument|birthcertdos_expdate|DoS or Abroad Birth Certificate Expiration Date|txt:txt|0x04",
"entity:docid=birthcertdos:xblk:xdocument|birthcertdos_info|DoS or Abroad Birth Certificate Information|txt:txt|0x00",
"entity:docid=usbirthcert:desc:xdocument|usbirthcert_device|US Birth Certificate Capture Device|txt:txt|0x00",
"entity:docid=usbirthcert:authval:xdocument|usbirthcert_id|US Birth Certificate ID|txt:txt|0x00",
"entity:docid=usbirthcert:jpgpic:xdocument|usbirthcert_visible|US Birth Certificate Visible Image|b64:bin|0x00",
"entity:docid=usbirthcert:issdate:xdocument|usbirthcert_issdate|US Birth Certificate Issue Date|txt:txt|0x04",
"entity:docid=usbirthcert:expdate:xdocument|usbirthcert_expdate|US Birth Certificate Expiration Date|txt:txt|0x04",
"entity:docid=usbirthcert:xblk:xdocument|usbirthcert_info|US Birth Certificate Information|txt:txt|0x00",
"entity:docid=uscitizedid:desc:xdocument|uscitizedid_device|US Citizen ID Card Capture Device|txt:txt|0x00",
"entity:docid=uscitizedid:authval:xdocument|uscitizedid_id|US Citizen ID Card ID|txt:txt|0x00",
"entity:docid=uscitizedid:jpgpic:xdocument|uscitizedid_visible|US Citizen ID Card Visible Image|b64:bin|0x00",
"entity:docid=uscitizedid:issdate:xdocument|uscitizedid_issdate|US Citizen ID Card Issue Date|txt:txt|0x04",
"entity:docid=uscitizedid:expdate:xdocument|uscitizedid_expdate|US Citizen ID Card Expiration Date|txt:txt|0x04",
"entity:docid=uscitizedid:xblk:xdocument|uscitizedid_info|US Citizen ID Card Information|txt:txt|0x00",
"entity:docid=formds1838:desc:xdocument|formds1838_device|DS-1838 Capture Device|txt:txt|0x00",
"entity:docid=formds1838:authval:xdocument|formds1838_id|DS-1838 ID|txt:txt|0x00",
"entity:docid=formds1838:jpgpic:xdocument|formds1838_visible|DS-1838 Visible Image|b64:bin|0x00",
"entity:docid=formds1838:issdate:xdocument|formds1838_issdate|DS-1838 Issue Date|txt:txt|0x04",
"entity:docid=formds1838:expdate:xdocument|formds1838_expdate|DS-1838 Expiration Date|txt:txt|0x04",
"entity:docid=formds1838:xblk:xdocument|formds1838_info|DS-1838 Information|txt:txt|0x00",
"entity:docid=other:desc:xdocument|other_device|Other Capture Device|txt:txt|0x00",
"entity:docid=other:authval:xdocument|other_id|Other ID|txt:txt|0x00",
"entity:docid=other:jpgpic:xdocument|other_visible|Other Visible Image|b64:bin|0x00",
"entity:docid=other:issdate:xdocument|other_issdate|Other Issue Date|txt:txt|0x04",
"entity:docid=other:expdate:xdocument|other_expdate|Other Expiration Date|txt:txt|0x04",
"entity:docid=other:xblk:xdocument|other_info|Other Information|txt:txt|0x00",
"entity:docid=toldoc:desc:xdocument|tentativeletter_device|T.O.L. Capture Device|txt:txt|0x00",
"entity:docid=toldoc:authval:xdocument|tentativeletter_id|T.O.L. ID|txt:txt|0x00",
"entity:docid=toldoc:jpgpic:xdocument|tentativeletter_visible|T.O.L. Visible Image|b64:bin|0x00",
"entity:docid=toldoc:issdate:xdocument|tentativeletter_issdate|T.O.L. Issue Date|txt:txt|0x04",
"entity:docid=toldoc:expdate:xdocument|tentativeletter_expdate|T.O.L. Expiration Date|txt:txt|0x04",
"entity:docid=toldoc:xblk:xdocument|tentativeletter_info|T.O.L. Information|txt:txt|0x00",
"entity:docid=verify_passport:desc:xdocument|verify_passport_device|Verifier US Passport Capture Device|txt:txt|0x00",
"entity:docid=verify_passport:authval:xdocument|verify_passport_id|Verifier US Passport ID|txt:txt|0x00",
"entity:docid=verify_passport:jpgpic:xdocument|verify_passport_visible|Verifier US Passport Visible Image|b64:bin|0x00",
"entity:docid=verify_passport:issdate:xdocument|verify_passport_issdate|Verifier US Passport Issue Date|txt:txt|0x04",
"entity:docid=verify_passport:expdate:xdocument|verify_passport_expdate|Verifier US Passport Expiration Date|txt:txt|0x04",
"entity:docid=verify_passport:xblk:xdocument|verify_passport_info|US Passport Information|txt:txt|0x00",
"entity:docid=verify_driverslic:desc:xdocument|verify_driverslic_device|Verify Drivers License Capture Device|txt:txt|0x00",
"entity:docid=verify_driverslic:authval:xdocument|verify_driverslic_id|Verify Drivers License ID|txt:txt|0x00",
"entity:docid=verify_driverslic:jpgpic:xdocument|verify_driverslic_visible|Verify Drivers License Visible Image|b64:bin|0x00",
"entity:docid=verify_driverslic:issdate:xdocument|verify_driverslic_issdate|Verify Drivers License Issue Date|txt:txt|0x04",
"entity:docid=verify_driverslic:expdate:xdocument|verify_driverslic_expdate|Verify Drivers License Expiration Date|txt:txt|0x04",
"entity:docid=verify_driverslic:xblk:xdocument|verify_driverslic_info|Verify Drivers License Information|txt:txt|0x00",
"entity:docid=otherpiv:desc:xdocument|otherpiv_device|Other PIV Card Capture Device|txt:txt|0x00",
"entity:docid=otherpiv:authval:xdocument|otherpiv_id|Other PIV Card ID|txt:txt|0x00",
"entity:docid=otherpiv:jpgpic:xdocument|otherpiv_visible|Other PIV Card Visible Image|b64:bin|0x00",
"entity:docid=otherpiv:issdate:xdocument|otherpiv_issdate|Other PIV Card Issue Date|txt:txt|0x04",
"entity:docid=otherpiv:expdate:xdocument|otherpiv_expdate|Other PIV Card Expiration Date|txt:txt|0x04",
"entity:docid=otherpiv:xblk:xdocument|otherpiv_info|Other PIV Card Information|txt:txt|0x00",
"entity:docid=disclosure:desc:xdocument|disclosure_device|Disclosure Capture Device|txt:txt|0x00",
"entity:docid=disclosure:authval:xdocument|disclosure_id|Disclosure ID|txt:txt|0x00",
"entity:docid=disclosure:jpgpic:xdocument|disclosure_visible|Disclosure Visible Image|b64:bin|0x00",
"entity:docid=disclosure:issdate:xdocument|disclosure_issdate|Disclosure Issue Date|txt:txt|0x04",
"entity:docid=disclosure:expdate:xdocument|disclosure_expdate|Disclosure Expiration Date|txt:txt|0x04",
"entity:docid=disclosure:xblk:xdocument|disclosure_info|Disclosure Information|txt:txt|0x00",
"entity:docid=passport_secondary:desc:xdocument|passport_device_secondary|US Passport Capture Device|txt:txt|0x00",
"entity:docid=passport_secondary:authval:xdocument|passport_id_secondary|US Passport ID|txt:txt|0x00",
"entity:docid=passport_secondary:jpgpic:xdocument|passport_visible_secondary|US Passport Visible Image|b64:bin|0x00",
"entity:docid=passport_secondary:issdate:xdocument|passport_issdate_secondary|US Passport Issue Date|txt:txt|0x04",
"entity:docid=passport_secondary:expdate:xdocument|passport_expdate_secondary|US Passport Expiration Date|txt:txt|0x04",
"entity:docid=passport_secondary:xblk:xdocument|passport_info_secondary|US Passport Information|txt:txt|0x00",
"entity:docid=cizenship_secondary:desc:xdocument|cizenship_device_secondary|Certificate of US Citizenship Capture Device|txt:txt|0x00",
"entity:docid=cizenship_secondary:authval:xdocument|cizenship_id_secondary|Certificate of US Citizenship ID|txt:txt|0x00",
"entity:docid=cizenship_secondary:jpgpic:xdocument|cizenship_visible_secondary|Certificate of US Citizenship Visible Image|b64:bin|0x00",
"entity:docid=cizenship_secondary:issdate:xdocument|cizenship_issdate_secondary|Certificate of US Citizenship Issue Date|txt:txt|0x04",
"entity:docid=cizenship_secondary:expdate:xdocument|cizenship_expdate_secondary|Certificate of US Citizenship Expiration Date|txt:txt|0x04",
"entity:docid=cizenship_secondary:xblk:xdocument|cizenship_info_secondary|Certificate of US Citizenship Information|txt:txt|0x00",
"entity:docid=naturalization_secondary:desc:xdocument|naturalization_device_secondary|Certificate of Naturalization Capture Device|txt:txt|0x00",
"entity:docid=naturalization_secondary:authval:xdocument|naturalization_id_secondary|Certificate of Naturalization ID|txt:txt|0x00",
"entity:docid=naturalization_secondary:jpgpic:xdocument|naturalization_visible_secondary|Certificate of Naturalization Visible Image|b64:bin|0x00",
"entity:docid=naturalization_secondary:issdate:xdocument|naturalization_issdate_secondary|Certificate of Naturalization Issue Date|txt:txt|0x04",
"entity:docid=naturalization_secondary:expdate:xdocument|naturalization_expdate_secondary|Certificate of Naturalization Expiration Date|txt:txt|0x04",
"entity:docid=naturalization_secondary:xblk:xdocument|naturalization_info_secondary|Certificate of Naturalization Information|txt:txt|0x00",
"entity:docid=foreignpassport_secondary:desc:xdocument|foreignpassport_device_secondary|Foreign Passport Capture Device|txt:txt|0x00",
"entity:docid=foreignpassport_secondary:authval:xdocument|foreignpassport_id_secondary|Foreign Passport ID|txt:txt|0x00",
"entity:docid=foreignpassport_secondary:jpgpic:xdocument|foreignpassport_visible_secondary|Foreign Passport Visible Image|b64:bin|0x00",
"entity:docid=foreignpassport_secondary:issdate:xdocument|foreignpassport_issdate_secondary|Foreign Passport Issue Date|txt:txt|0x04",
"entity:docid=foreignpassport_secondary:expdate:xdocument|foreignpassport_expdate_secondary|Foreign Passport Expiration Date|txt:txt|0x04",
"entity:docid=foreignpassport_secondary:xblk:xdocument|foreignpassport_info_secondary|Foreign Passport Information|txt:txt|0x00",
"entity:docid=resident_secondary:desc:xdocument|resident_device_secondary|Permanent Resident or Alien Registration Card Capture Device|txt:txt|0x00",
"entity:docid=resident_secondary:authval:xdocument|resident_id_secondary|Permanent Resident or Alien Registration Card ID|txt:txt|0x00",
"entity:docid=resident_secondary:jpgpic:xdocument|resident_visible_secondary|Permanent Resident or Alien Registration Card Visible Image|b64:bin|0x00",
"entity:docid=resident_secondary:issdate:xdocument|resident_issdate_secondary|Permanent Resident or Alien Registration Card Issue Date|txt:txt|0x04",
"entity:docid=resident_secondary:expdate:xdocument|resident_expdate_secondary|Permanent Resident or Alien Registration Card Expiration Date|txt:txt|0x04",
"entity:docid=resident_secondary:xblk:xdocument|resident_info_secondary|Permanent Resident or Alien Registration Card Information|txt:txt|0x00",
"entity:docid=tempresident_secondary:desc:xdocument|tempresident_device_secondary|Temporary Resident Card Capture Device|txt:txt|0x00",
"entity:docid=tempresident_secondary:authval:xdocument|tempresident_id_secondary|Temporary Resident Card ID|txt:txt|0x00",
"entity:docid=tempresident_secondary:jpgpic:xdocument|tempresident_visible_secondary|Temporary Resident Card Visible Image|b64:bin|0x00",
"entity:docid=tempresident_secondary:issdate:xdocument|tempresident_issdate_secondary|Temporary Resident Card Issue Date|txt:txt|0x04",
"entity:docid=tempresident_secondary:expdate:xdocument|tempresident_expdate_secondary|Temporary Resident Card Expiration Date|txt:txt|0x04",
"entity:docid=tempresident_secondary:xblk:xdocument|tempresident_info_secondary|Temporary Resident Card Information|txt:txt|0x00",
"entity:docid=employment_secondary:desc:xdocument|employment_device_secondary|Employment Authorization Card Capture Device|txt:txt|0x00",
"entity:docid=employment_secondary:authval:xdocument|employment_id_secondary|Employment Authorization Card ID|txt:txt|0x00",
"entity:docid=employment_secondary:jpgpic:xdocument|employment_visible_secondary|Employment Authorization Card Visible Image|b64:bin|0x00",
"entity:docid=employment_secondary:issdate:xdocument|employment_issdate_secondary|Employment Authorization Card Issue Date|txt:txt|0x04",
"entity:docid=employment_secondary:expdate:xdocument|employment_expdate_secondary|Employment Authorization Card Expiration Date|txt:txt|0x04",
"entity:docid=employment_secondary:xblk:xdocument|employment_info_secondary|Employment Authorization Card Information|txt:txt|0x00",
"entity:docid=reentry_secondary:desc:xdocument|reentry_device_secondary|Reentry Permit Capture Device|txt:txt|0x00",
"entity:docid=reentry_secondary:authval:xdocument|reentry_id_secondary|Reentry Permit ID|txt:txt|0x00",
"entity:docid=reentry_secondary:jpgpic:xdocument|reentry_visible_secondary|Reentry Permit Visible Image|b64:bin|0x00",
"entity:docid=reentry_secondary:issdate:xdocument|reentry_issdate_secondary|Reentry Permit Issue Date|txt:txt|0x04",
"entity:docid=reentry_secondary:expdate:xdocument|reentry_expdate_secondary|Reentry Permit Expiration Date|txt:txt|0x04",
"entity:docid=reentry_secondary:xblk:xdocument|reentry_info_secondary|Reentry Permit Information|txt:txt|0x00",
"entity:docid=refugee_secondary:desc:xdocument|refugee_device_secondary|Refugee Travel Document Capture Device|txt:txt|0x00",
"entity:docid=refugee_secondary:authval:xdocument|refugee_id_secondary|Refugee Travel Document ID|txt:txt|0x00",
"entity:docid=refugee_secondary:jpgpic:xdocument|refugee_visible_secondary|Refugee Travel Document Visible Image|b64:bin|0x00",
"entity:docid=refugee_secondary:issdate:xdocument|refugee_issdate_secondary|Refugee Travel Document Issue Date|txt:txt|0x04",
"entity:docid=refugee_secondary:expdate:xdocument|refugee_expdate_secondary|Refugee Travel Document Expiration Date|txt:txt|0x04",
"entity:docid=refugee_secondary:xblk:xdocument|refugee_info_secondary|Refugee Travel Document Information|txt:txt|0x00",
"entity:docid=dhsemplyment_secondary:desc:xdocument|dhsemplyment_device_secondary|DHS Employment Authorization Document Capture Device|txt:txt|0x00",
"entity:docid=dhsemplyment_secondary:authval:xdocument|dhsemplyment_id_secondary|DHS Employment Authorization Document ID|txt:txt|0x00",
"entity:docid=dhsemplyment_secondary:jpgpic:xdocument|dhsemplyment_visible_secondary|DHS Employment Authorization Document Visible Image|b64:bin|0x00",
"entity:docid=dhsemplyment_secondary:issdate:xdocument|dhsemplyment_issdate_secondary|DHS Employment Authorization Document Issue Date|txt:txt|0x04",
"entity:docid=dhsemplyment_secondary:expdate:xdocument|dhsemplyment_expdate_secondary|DHS Employment Authorization Document Expiration Date|txt:txt|0x04",
"entity:docid=dhsemplyment_secondary:xblk:xdocument|dhsemplyment_info_secondary|DHS Employment Authorization Document Information|txt:txt|0x00",
"entity:docid=driverslic_secondary:desc:xdocument|driverslic_device_secondary|Drivers License Capture Device|txt:txt|0x00",
"entity:docid=driverslic_secondary:authval:xdocument|driverslic_id_secondary|Drivers License ID|txt:txt|0x00",
"entity:docid=driverslic_secondary:jpgpic:xdocument|driverslic_visible_secondary|Drivers License Visible Image|b64:bin|0x00",
"entity:docid=driverslic_secondary:issdate:xdocument|driverslic_issdate_secondary|Drivers License Issue Date|txt:txt|0x04",
"entity:docid=driverslic_secondary:expdate:xdocument|driverslic_expdate_secondary|Drivers License Expiration Date|txt:txt|0x04",
"entity:docid=driverslic_secondary:xblk:xdocument|driverslic_info_secondary|Drivers License Information|txt:txt|0x00",
"entity:docid=govid_secondary:desc:xdocument|govid_device_secondary|Other Federal, State or Local ID Card Capture Device|txt:txt|0x00",
"entity:docid=govid_secondary:authval:xdocument|govid_id_secondary|Other Federal, State or Local ID Card ID|txt:txt|0x00",
"entity:docid=govid_secondary:jpgpic:xdocument|govid_visible_secondary|Other Federal, State or Local ID Card Visible Image|b64:bin|0x00",
"entity:docid=govid_secondary:issdate:xdocument|govid_issdate_secondary|Other Federal, State or Local ID Card Issue Date|txt:txt|0x04",
"entity:docid=govid_secondary:expdate:xdocument|govid_expdate_secondary|Other Federal, State or Local ID Card Expiration Date|txt:txt|0x04",
"entity:docid=govid_secondary:xblk:xdocument|govid_info_secondary|Other Federal, State or Local ID Card Information|txt:txt|0x00",
"entity:docid=schoolid_secondary:desc:xdocument|schoolid_device_secondary|School ID Card Capture Device|txt:txt|0x00",
"entity:docid=schoolid_secondary:authval:xdocument|schoolid_id_secondary|School ID Card ID|txt:txt|0x00",
"entity:docid=schoolid_secondary:jpgpic:xdocument|schoolid_visible_secondary|School ID Card Visible Image|b64:bin|0x00",
"entity:docid=schoolid_secondary:issdate:xdocument|schoolid_issdate_secondary|School ID Card Issue Date|txt:txt|0x04",
"entity:docid=schoolid_secondary:expdate:xdocument|schoolid_expdate_secondary|School ID Card Expiration Date|txt:txt|0x04",
"entity:docid=schoolid_secondary:xblk:xdocument|schoolid_info_secondary|School ID Card Information|txt:txt|0x00",
"entity:docid=voters_secondary:desc:xdocument|voters_device_secondary|Voters Registration Card Capture Device|txt:txt|0x00",
"entity:docid=voters_secondary:authval:xdocument|voters_id_secondary|Voters Registration Card ID|txt:txt|0x00",
"entity:docid=voters_secondary:jpgpic:xdocument|voters_visible_secondary|Voters Registration Card Visible Image|b64:bin|0x00",
"entity:docid=voters_secondary:issdate:xdocument|voters_issdate_secondary|Voters Registration Card Issue Date|txt:txt|0x04",
"entity:docid=voters_secondary:expdate:xdocument|voters_expdate_secondary|Voters Registration Card Expiration Date|txt:txt|0x04",
"entity:docid=voters_secondary:xblk:xdocument|voters_info_secondary|Voters Registration Card Information|txt:txt|0x00",
"entity:docid=usmilid_secondary:desc:xdocument|usmilid_device_secondary|US Military Card Capture Device|txt:txt|0x00",
"entity:docid=usmilid_secondary:authval:xdocument|usmilid_id_secondary|US Military Card ID|txt:txt|0x00",
"entity:docid=usmilid_secondary:jpgpic:xdocument|usmilid_visible_secondary|US Military Card Visible Image|b64:bin|0x00",
"entity:docid=usmilid_secondary:issdate:xdocument|usmilid_issdate_secondary|US Military Card Issue Date|txt:txt|0x04",
"entity:docid=usmilid_secondary:expdate:xdocument|usmilid_expdate_secondary|US Military Card Expiration Date|txt:txt|0x04",
"entity:docid=usmilid_secondary:xblk:xdocument|usmilid_info_secondary|US Military Card Information|txt:txt|0x00",
"entity:docid=usmildependant_secondary:desc:xdocument|usmildependant_device_secondary|US Miltary Dependant ID Card Capture Device|txt:txt|0x00",
"entity:docid=usmildependant_secondary:authval:xdocument|usmildependant_id_secondary|US Miltary Dependant ID Card ID|txt:txt|0x00",
"entity:docid=usmildependant_secondary:jpgpic:xdocument|usmildependant_visible_secondary|US Miltary Dependant ID Card Visible Image|b64:bin|0x00",
"entity:docid=usmildependant_secondary:issdate:xdocument|usmildependant_issdate_secondary|US Miltary Dependant ID Card Issue Date|txt:txt|0x04",
"entity:docid=usmildependant_secondary:expdate:xdocument|usmildependant_expdate_secondary|US Miltary Dependant ID Card Expiration Date|txt:txt|0x04",
"entity:docid=usmildependant_secondary:xblk:xdocument|usmildependant_info_secondary|US Miltary Dependant ID Card Information|txt:txt|0x00",
"entity:docid=uscgmac_secondary:desc:xdocument|uscgmac_device_secondary|US Coast Guard Mariner Card Capture Device|txt:txt|0x00",
"entity:docid=uscgmac_secondary:authval:xdocument|uscgmac_id_secondary|US Coast Guard Mariner Card ID|txt:txt|0x00",
"entity:docid=uscgmac_secondary:jpgpic:xdocument|uscgmac_visible_secondary|US Coast Guard Mariner Card Visible Image|b64:bin|0x00",
"entity:docid=uscgmac_secondary:issdate:xdocument|uscgmac_issdate_secondary|US Coast Guard Mariner Card Issue Date|txt:txt|0x04",
"entity:docid=uscgmac_secondary:expdate:xdocument|uscgmac_expdate_secondary|US Coast Guard Mariner Card Expiration Date|txt:txt|0x04",
"entity:docid=uscgmac_secondary:xblk:xdocument|uscgmac_info_secondary|US Coast Guard Mariner Card Information|txt:txt|0x00",
"entity:docid=nativeamerican_secondary:desc:xdocument|nativeamerican_device_secondary|Native American Tribal Document Capture Device|txt:txt|0x00",
"entity:docid=nativeamerican_secondary:authval:xdocument|nativeamerican_id_secondary|Native American Tribal Document ID|txt:txt|0x00",
"entity:docid=nativeamerican_secondary:jpgpic:xdocument|nativeamerican_visible_secondary|Native American Tribal Document Visible Image|b64:bin|0x00",
"entity:docid=nativeamerican_secondary:issdate:xdocument|nativeamerican_issdate_secondary|Native American Tribal Document Issue Date|txt:txt|0x04",
"entity:docid=nativeamerican_secondary:expdate:xdocument|nativeamerican_expdate_secondary|Native American Tribal Document Expiration Date|txt:txt|0x04",
"entity:docid=nativeamerican_secondary:xblk:xdocument|nativeamerican_info_secondary|Native American Tribal Document Information|txt:txt|0x00",
"entity:docid=schoolrecord_secondary:desc:xdocument|schoolrecord_device_secondary|School Record or Report Card Capture Device|txt:txt|0x00",
"entity:docid=schoolrecord_secondary:authval:xdocument|schoolrecord_id_secondary|School Record or Report Card ID|txt:txt|0x00",
"entity:docid=schoolrecord_secondary:jpgpic:xdocument|schoolrecord_visible_secondary|School Record or Report Card Visible Image|b64:bin|0x00",
"entity:docid=schoolrecord_secondary:issdate:xdocument|schoolrecord_issdate_secondary|School Record or Report Card Issue Date|txt:txt|0x04",
"entity:docid=schoolrecord_secondary:expdate:xdocument|schoolrecord_expdate_secondary|School Record or Report Card Expiration Date|txt:txt|0x04",
"entity:docid=schoolrecord_secondary:xblk:xdocument|schoolrecord_info_secondary|School Record or Report Card Information|txt:txt|0x00",
"entity:docid=medrecord_secondary:desc:xdocument|medrecord_device_secondary|Medical Record Capture Device|txt:txt|0x00",
"entity:docid=medrecord_secondary:authval:xdocument|medrecord_id_secondary|Medical Record ID|txt:txt|0x00",
"entity:docid=medrecord_secondary:jpgpic:xdocument|medrecord_visible_secondary|Medical Record Visible Image|b64:bin|0x00",
"entity:docid=medrecord_secondary:issdate:xdocument|medrecord_issdate_secondary|Medical Record Issue Date|txt:txt|0x04",
"entity:docid=medrecord_secondary:expdate:xdocument|medrecord_expdate_secondary|Medical Record Expiration Date|txt:txt|0x04",
"entity:docid=medrecord_secondary:xblk:xdocument|medrecord_info_secondary|Medical Record Information|txt:txt|0x00",
"entity:docid=nurseryrecord_secondary:desc:xdocument|nurseryrecord_device_secondary|Nursery School Record Capture Device|txt:txt|0x00",
"entity:docid=nurseryrecord_secondary:authval:xdocument|nurseryrecord_id_secondary|Nursery School Record ID|txt:txt|0x00",
"entity:docid=nurseryrecord_secondary:jpgpic:xdocument|nurseryrecord_visible_secondary|Nursery School Record Visible Image|b64:bin|0x00",
"entity:docid=nurseryrecord_secondary:issdate:xdocument|nurseryrecord_issdate_secondary|Nursery School Record Issue Date|txt:txt|0x04",
"entity:docid=nurseryrecord_secondary:expdate:xdocument|nurseryrecord_expdate_secondary|Nursery School Record Expiration Date|txt:txt|0x04",
"entity:docid=nurseryrecord_secondary:xblk:xdocument|nurseryrecord_info_secondary|Nursery School Record Information|txt:txt|0x00",
"entity:docid=ussocsec_secondary:desc:xdocument|ussocsec_device_secondary|US Social Security Card Capture Device|txt:txt|0x00",
"entity:docid=ussocsec_secondary:authval:xdocument|ussocsec_id_secondary|US Social Security Card ID|txt:txt|0x00",
"entity:docid=ussocsec_secondary:jpgpic:xdocument|ussocsec_visible_secondary|US Social Security Card Visible Image|b64:bin|0x00",
"entity:docid=ussocsec_secondary:issdate:xdocument|ussocsec_issdate_secondary|US Social Security Card Issue Date|txt:txt|0x04",
"entity:docid=ussocsec_secondary:expdate:xdocument|ussocsec_expdate_secondary|US Social Security Card Expiration Date|txt:txt|0x04",
"entity:docid=ussocsec_secondary:xblk:xdocument|ussocsec_info_secondary|US Social Security Card Information|txt:txt|0x00",
"entity:docid=birthcertdos_secondary:desc:xdocument|birthcertdos_device_secondary|DoS or Abroad Birth Certificate Capture Device|txt:txt|0x00",
"entity:docid=birthcertdos_secondary:authval:xdocument|birthcertdos_id_secondary|DoS or Abroad Birth Certificate ID|txt:txt|0x00",
"entity:docid=birthcertdos_secondary:jpgpic:xdocument|birthcertdos_visible_secondary|DoS or Abroad Birth Certificate Visible Image|b64:bin|0x00",
"entity:docid=birthcertdos_secondary:issdate:xdocument|birthcertdos_issdate_secondary|DoS or Abroad Birth Certificate Issue Date|txt:txt|0x04",
"entity:docid=birthcertdos_secondary:expdate:xdocument|birthcertdos_expdate_secondary|DoS or Abroad Birth Certificate Expiration Date|txt:txt|0x04",
"entity:docid=birthcertdos_secondary:xblk:xdocument|birthcertdos_info_secondary|DoS or Abroad Birth Certificate Information|txt:txt|0x00",
"entity:docid=usbirthcert_secondary:desc:xdocument|usbirthcert_device_secondary|US Birth Certificate Capture Device|txt:txt|0x00",
"entity:docid=usbirthcert_secondary:authval:xdocument|usbirthcert_id_secondary|US Birth Certificate ID|txt:txt|0x00",
"entity:docid=usbirthcert_secondary:jpgpic:xdocument|usbirthcert_visible_secondary|US Birth Certificate Visible Image|b64:bin|0x00",
"entity:docid=usbirthcert_secondary:issdate:xdocument|usbirthcert_issdate_secondary|US Birth Certificate Issue Date|txt:txt|0x04",
"entity:docid=usbirthcert_secondary:expdate:xdocument|usbirthcert_expdate_secondary|US Birth Certificate Expiration Date|txt:txt|0x04",
"entity:docid=usbirthcert_secondary:xblk:xdocument|usbirthcert_info_secondary|US Birth Certificate Information|txt:txt|0x00",
"entity:docid=uscitizedid_secondary:desc:xdocument|uscitizedid_device_secondary|US Citizen ID Card Capture Device|txt:txt|0x00",
"entity:docid=uscitizedid_secondary:authval:xdocument|uscitizedid_id_secondary|US Citizen ID Card ID|txt:txt|0x00",
"entity:docid=uscitizedid_secondary:jpgpic:xdocument|uscitizedid_visible_secondary|US Citizen ID Card Visible Image|b64:bin|0x00",
"entity:docid=uscitizedid_secondary:issdate:xdocument|uscitizedid_issdate_secondary|US Citizen ID Card Issue Date|txt:txt|0x04",
"entity:docid=uscitizedid_secondary:expdate:xdocument|uscitizedid_expdate_secondary|US Citizen ID Card Expiration Date|txt:txt|0x04",
"entity:docid=uscitizedid_secondary:xblk:xdocument|uscitizedid_info_secondary|US Citizen ID Card Information|txt:txt|0x00",
"entity:docid=formds1838_secondary:desc:xdocument|formds1838_device_secondary|DS-1838 Capture Device|txt:txt|0x00",
"entity:docid=formds1838_secondary:authval:xdocument|formds1838_id_secondary|DS-1838 ID|txt:txt|0x00",
"entity:docid=formds1838_secondary:jpgpic:xdocument|formds1838_visible_secondary|DS-1838 Visible Image|b64:bin|0x00",
"entity:docid=formds1838_secondary:issdate:xdocument|formds1838_issdate_secondary|DS-1838 Issue Date|txt:txt|0x04",
"entity:docid=formds1838_secondary:expdate:xdocument|formds1838_expdate_secondary|DS-1838 Expiration Date|txt:txt|0x04",
"entity:docid=formds1838_secondary:xblk:xdocument|formds1838_info_secondary|DS-1838 Information|txt:txt|0x00",
"entity:docid=other_secondary:desc:xdocument|other_device_secondary|Other Capture Device|txt:txt|0x00",
"entity:docid=other_secondary:authval:xdocument|other_id_secondary|Other ID|txt:txt|0x00",
"entity:docid=other_secondary:jpgpic:xdocument|other_visible_secondary|Other Visible Image|b64:bin|0x00",
"entity:docid=other_secondary:issdate:xdocument|other_issdate_secondary|Other Issue Date|txt:txt|0x04",
"entity:docid=other_secondary:expdate:xdocument|other_expdate_secondary|Other Expiration Date|txt:txt|0x04",
"entity:docid=other_secondary:xblk:xdocument|other_info_secondary|Other Information|txt:txt|0x00",
"entity:docid=toldoc_secondary:desc:xdocument|tentativeletter_device_secondary|T.O.L. Capture Device|txt:txt|0x00",
"entity:docid=toldoc_secondary:authval:xdocument|tentativeletter_id_secondary|T.O.L. ID|txt:txt|0x00",
"entity:docid=toldoc_secondary:jpgpic:xdocument|tentativeletter_visible_secondary|T.O.L. Visible Image|b64:bin|0x00",
"entity:docid=toldoc_secondary:issdate:xdocument|tentativeletter_issdate_secondary|T.O.L. Issue Date|txt:txt|0x04",
"entity:docid=toldoc_secondary:expdate:xdocument|tentativeletter_expdate_secondary|T.O.L. Expiration Date|txt:txt|0x04",
"entity:docid=toldoc_secondary:xblk:xdocument|tentativeletter_info_secondary|T.O.L. Information|txt:txt|0x00",
"entity:docid=disclosure_secondary:desc:xdocument|disclosure_device_secondary|Disclosure Capture Device|txt:txt|0x00",
"entity:docid=disclosure_secondary:authval:xdocument|disclosure_id_secondary|Disclosure ID|txt:txt|0x00",
"entity:docid=disclosure_secondary:jpgpic:xdocument|disclosure_visible_secondary|Disclosure Visible Image|b64:bin|0x00",
"entity:docid=disclosure_secondary:issdate:xdocument|disclosure_issdate_secondary|Disclosure Issue Date|txt:txt|0x04",
"entity:docid=disclosure_secondary:expdate:xdocument|disclosure_expdate_secondary|Disclosure Expiration Date|txt:txt|0x04",
"entity:docid=disclosure_secondary:xblk:xdocument|disclosure_info_secondary|Disclosure Information|txt:txt|0x00",
"entity:docid=otherpiv_secondary:desc:xdocument|otherpiv_device_secondary|Other PIV Card Capture Device|txt:txt|0x00",
"entity:docid=otherpiv_secondary:authval:xdocument|otherpiv_id_secondary|Other PIV Card ID|txt:txt|0x00",
"entity:docid=otherpiv_secondary:jpgpic:xdocument|otherpiv_visible_secondary|Other PIV Card Visible Image|b64:bin|0x00",
"entity:docid=otherpiv_secondary:issdate:xdocument|otherpiv_issdate_secondary|Other PIV Card Issue Date|txt:txt|0x04",
"entity:docid=otherpiv_secondary:expdate:xdocument|otherpiv_expdate_secondary|Other PIV Card Expiration Date|txt:txt|0x04",
"entity:docid=otherpiv_secondary:xblk:xdocument|otherpiv_info_secondary|Other PIV Card Information|txt:txt|0x00",
"entity:procid=ichk,ounit=".$wflow.":status:process|ichk_status|Impersonation Check Status|txt:txt|0x00",
"entity:procid=ichk,ounit=".$wflow.":rem:process|ichk_rem|Impersonation Check Remarks|txt:txt|0x00",
"entity:procid=ichk,ounit=".$wflow.":startdate:process|ichk_startdate|Impersonation Check Start Date|txt:txt|0x04",
"entity:procid=ichk,ounit=".$wflow.":enddate:process|ichk_enddate|Impersonation Check End Date|txt:txt|0x04",
"entity:procid=ichk,ounit=".$wflow.":startby:process|ichk_startby|Impersonation Check Start By|txt:txt|0x00",
"entity:procid=ichk,ounit=".$wflow.":endby:process|ichk_endby|Impersonation Check End By|txt:txt|0x00",
"entity:procid=ichk,ounit=".$wflow.":objectlog:process|ichk_objectlog|Impersonation Check Objectlog|txt:txt|0x00",
"entity:sysid=logs:objectlog:xsystem|ichk_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=fpcap,ounit=".$wflow.":status:process|fpcap_status|Fingerprint Capture Status|txt:txt|0x00",
"entity:procid=fpcap,ounit=".$wflow.":rem:process|fpcap_rem|Fingerprint Capture Remarks|txt:txt|0x00",
"entity:procid=fpcap,ounit=".$wflow.":startdate:process|fpcap_startdate|Fingerprint Capture Start Date|txt:txt|0x04",
"entity:procid=fpcap,ounit=".$wflow.":enddate:process|fpcap_enddate|Fingerprint Capture End Date|txt:txt|0x04",
"entity:procid=fpcap,ounit=".$wflow.":startby:process|fpcap_startby|Fingerprint Capture Start By|txt:txt|0x00",
"entity:procid=fpcap,ounit=".$wflow.":endby:process|fpcap_endby|Fingerprint Capture End By|txt:txt|0x00",
"entity:procid=fpcap,ounit=".$wflow.":objectlog:process|fpcap_objectlog|Fingerprint Capture Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|fpcap_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=doccap,ounit=".$wflow.":status:process|doccap_status|Document Capture Status|txt:txt|0x00",
"entity:procid=doccap,ounit=".$wflow.":rem:process|doccap_rem|Document Capture Remarks|txt:txt|0x00",
"entity:procid=doccap,ounit=".$wflow.":startdate:process|doccap_startdate|Document Capture Start Date|txt:txt|0x04",
"entity:procid=doccap,ounit=".$wflow.":enddate:process|doccap_enddate|Document Capture End Date|txt:txt|0x04",
"entity:procid=doccap,ounit=".$wflow.":startby:process|doccap_startby|Document Capture Start By|txt:txt|0x00",
"entity:procid=doccap,ounit=".$wflow.":endby:process|doccap_endby|Document Capture End By|txt:txt|0x00",
"entity:procid=doccap,ounit=".$wflow.":objectlog:process|doccap_objectlog|Document Capture Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|doccap_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=photocap,ounit=".$wflow.":status:process|photocap_status|Portrait Capture Status|txt:txt|0x00",
"entity:procid=photocap,ounit=".$wflow.":rem:process|photocap_rem|Portrait Capture Remarks|txt:txt|0x00",
"entity:procid=photocap,ounit=".$wflow.":startdate:process|photocap_startdate|Portrait Capture Start Date|txt:txt|0x04",
"entity:procid=photocap,ounit=".$wflow.":enddate:process|photocap_enddate|Portrait Capture End Date|txt:txt|0x04",
"entity:procid=photocap,ounit=".$wflow.":startby:process|photocap_startby|Portrait Capture Start By|txt:txt|0x00",
"entity:procid=photocap,ounit=".$wflow.":endby:process|photocap_endby|Portrait Capture End By|txt:txt|0x00",
"entity:procid=photocap,ounit=".$wflow.":objectlog:process|photocap_objectlog|Portrait Capture Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|photocap_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=print,ounit=".$wflow.":status:process|print_status|Print Package Status|txt:txt|0x00",
"entity:procid=print,ounit=".$wflow.":cardiin:process|print_cardIIN|Print Package Card IIN|txt:txt|0x08",
"entity:procid=print,ounit=".$wflow.":cardcin:process|print_cardCIN|Print Package Card CIN|txt:txt|0x08",
"entity:procid=print,ounit=".$wflow.":cstatus:process|print_cardCStatus|Print Package Card Status|txt:txt|0x08",
"entity:procid=print,ounit=".$wflow.":objectlog:process|print_objectlog|Print Package Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|print_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=print,ounit=".$wflow.":rem:process|print_rem|Print Package Remarks|txt:txt|0x00",
"entity:procid=ship,ounit=".$wflow.":status:process|ship_status|PIV Delivery Status|txt:txt|0x00",
"entity:procid=ship,ounit=".$wflow.":objectlog:process|ship_objectlog|PIV Delivery Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|ship_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=ship,ounit=".$wflow.":rem:process|ship_rem|PIV Delivery Remarks|txt:txt|0x00",
"entity:procid=activate,ounit=".$wflow.":status:process|activate_status|PIV Activation Status|txt:txt|0x00",
"entity:procid=activate,ounit=".$wflow.":objectlog:process|activate_objectlog|PIV Activation Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|activate_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=activate,ounit=".$wflow.":rem:process|activate_rem|PIV Activation Remarks|txt:txt|0x01",
"entity:procid=encode,ounit=".$wflow.":status:process|encode_status|PIV Encode Status|txt:txt|0x00",
"entity:procid=encode,ounit=".$wflow.":objectlog:process|encode_objectlog|PIV Encode Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|encode_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=encode,ounit=".$wflow.":rem:process|encode_rem|PIV Encode Remarks|txt:txt|0x00",
"entity:gcoid=token,procid=token,ounit=".$wflow.":upin:gco|userpin|User PIN|txt:txt|0x00",
"entity:procid=sponsor,ounit=".$wflow.":status:process|sponsor_status|Sponsor Status|txt:txt|0x00",
"entity:procid=sponsor,ounit=".$wflow.":objectlog:process|sponsor_objectlog|PIV Sponsor Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|sponsor_objectlog|System Object Log|txt:txt|0x01",
"entity:procid=sponsor,ounit=".$wflow.":rem:process|sponsor_rem|PIV Sponsor Remarks|txt:txt|0x00",
//"entity:procid=bgi,ounit=".$wflow.":status:process|bgi_status|BGI Status|txt:txt|0x00",
//"entity:procid=bgi,ounit=".$wflow.":objectlog:process|bgi_objectlog|BGI Object Log|txt:txt|0x01",
"hspd12:fbi:status:process|fbi_status|FBI Status|txt:txt|0x00",
"hspd12:fbi:objectlog:process|fbi_objectlog|FBI Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|fbi_objectlog|System Object Log|txt:txt|0x01",
"hspd12:bgi:status:process|bgi_status|BGI Status|txt:txt|0x00",
"hspd12:bgi:objectlog:process|bgi_objectlog|BGI Object Log|txt:txt|0x01",
"entity:sysid=logs:objectlog:xsystem|bgi_objectlog|System Object Log|txt:txt|0x01",
"entity:hght:entity|T2_HGT.A.3|Height|txt:txt|0x00",
"entity:weight:entity|T2_WGT.A.3|Weight|txt:txt|0x00",
"entity:pob:entity|T2_POB.A.2|Place of Birth|txt:txt|0x00",
"entity:nationality:entity|T2_CTZ.A.2|Citizenship|txt:txt|0x00",
"entity:hrclr:entity|T2_HAI.A.3|Hair Color|txt:txt|0x00",
"entity:gndr:entity|T2_SEX.A.1|Gender|txt:txt|0x00",
"entity:eyeclr:entity|T2_EYE.A.3|Eye Color|txt:txt|0x00",
"entity:race:entity|T2_RAC.A.1|Race|txt:txt|0x00",
"entity:gcoid=general:xblk:00250d:gco|PIV_Primary_DESC|PIV Primary Template Desc|txt:txt|0x00",
"entity:gcoid=general:xblk:002508:gco|SON|Person SON|txt:txt|0x00",
"entity:gcoid=general:xblk:00250A:gco|SOI|Person SOI|txt:txt|0x00",
"entity:firstname:entity|firstname|First Name|txt:txt|0x00",
"entity:mi:entity|mi|Middle Name|txt:txt|0x00",
"entity:lastname:entity|lastname|Last Name|txt:txt|0x00",
"entity:suffix:entity|suffix|Suffix|txt:txt|0x00",
"entity:dob:entity|dob|Date of Birth|txt:txt|0x04",
"entity:nationality:entity|nationality|Nationality|txt:txt|0x00",
"entity:gcoid=personal:xblk:0020A7:gco|dual|Dual Nationality|txt:txt|0x00",
"entity:gndr:entity|gender|Gender|txt:txt|0x00",
"entity:ssn:entity|ssn|Social Security Number|txt:txt|0x200",
"entity:upi:entity|fsn|Unique ID Number|txt:txt|0x00",
"entity:addrid=home:street:address|homestreet|Home Street|txt:txt|0x00",
"entity:gcoid=general:xblk:002351:gco|homeapartment|Apartment Number|txt:txt|0x00",
"entity:addrid=home:city:address|homecity|Home City|txt:txt|0x00",
"entity:addrid=home:st:address|homestate|Home State|txt:txt|0x00",
"entity:addrid=home:postcode:address|homezip|Home Zip Code|txt:txt|0x00",
"entity:emplid=usaccess:employer:employment|emplname|Employer Name|txt:txt|0x00",
"entity:emplid=usaccess:phone:employment|emplphone|Employer Phone|txt:txt|0x00",
"entity:emplid=usaccess:phonefax:employment|emplfax|Employer Fax|txt:txt|0x00",
"entity:emplid=usaccess:street:employment|emplstreet|Employer Street Address|txt:txt|0x00",
"entity:emplid=usaccess:suite:employment|emplsuite|Employer Suite|txt:txt|0x00",
"entity:emplid=usaccess:city:employment|emplcity|Employer City|txt:txt|0x00",
"entity:emplid=usaccess:st:employment|emplstate|Employer State|txt:txt|0x00",
"entity:emplid=usaccess:postcode:employment|emplzip|Employer Zip Code|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:0022a0:gco|escortauth|Escort Authority|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:0022a1:gco|accesshours|Hours of Access|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000056:gco|accesstype|Type of Access|txt:txt|0x00",
"entity:gcoid=contractor:xblk:0022a2:gco|cnumber|Contract Number|txt:txt|0x00",
"entity:gcoid=contractor:xblk:0022a5:gco|ccontract|Classified Contract|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000001:gco|sfirstname|State Requester First Name|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:002002:gco|smi|State Requester MI|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000003:gco|slastname|State Requester Last Name|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000004:gco|ssuffix|State Requester Suffix|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000005:gco|sphone|Requester Phone Number|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:00229c:gco|stype|Requester Type|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000007:gco|sother|Requester Type Other|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000008:gco|soffsym|Requester Office Symbol|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:002290:gco|sponsorid|Requester ID Card Number|txt:txt|0x00",
"entity:gcoid=sponsor:xblk:000006:gco|ssigdate|Requester Date Signed|txt:txt|0x04",
"entity:gcoid=token,procid=token,ounit=".$wflow.":xblk:002075:gco|crednumber|Card Number Issed|txt:txt|0x00",
"entity:gcoid=clearance:xblk:002401:gco|pinissued|Pin Issued|txt:txt|0x00",
"entity:gcoid=clearance:xblk:002402:gco|cardnumreturn|Card Number Returned|txt:txt|0x00",
"entity:gcoid=clearance:xblk:002400:gco|isstype|Issuance Type|txt:txt|0x00",
"entity:gcoid=token,procid=token,ounit=".$wflow.":xblk:000054:gco|cardtype|Card Type|txt:txt|0x00",
"entity:gcoid=clearance:xblk:00230a:gco|previousclearancelevel|Previous Clearance Level|txt:txt|0x00",
"entity:gcoid=clearance:xblk:002301:gco|currentclearancelevel|Current Clearance Level|txt:txt|0x00",
"entity:gcoid=clearance:xblk:002302:gco|dategranted|Date Granted|txt:txt|0x04",
"entity:gcoid=clearance:xblk:00230b:gco|grantingagency|Granting Agency|txt:txt|0x00",
"entity:gcoid=clearance:xblk:00230c:gco|processor|Processor|txt:txt|0x00",
"entity:gcoid=clearance:xblk:00230d:gco|issuer|Issuer Name|txt:txt|0x00",
"entity:gcoid=clearance:xblk:00230e:gco|supervisor|Supervisor Name|read|0x00",
"entity:gcoid=clearance:xblk:00230f:gco|dateissued|Date Issued|txt:txt|0x04",
//pending geoffs approval
"entity:gcoid=clearance:xblk:003101:gco|sciclearancestatus|SCI Clearance Status|txt:txt|0x00",
"entity:gcoid=clearance:xblk:003102:gco|dateauthorized|SCI Clearance Date Authorized|txt:txt|0x04",
"entity:gcoid=clearance:xblk:003103:gco|authorizedby|SCI Authorized By|txt:txt|0x00",
"entity:gcoid=clearance:xblk:003104:gco|accessstatus|SCI Access Status|txt:txt|0x00",
"entity:gcoid=clearance:xblk:003105:gco|dateauthorized2|INR Access Date Authorized|txt:txt|0x04",
"entity:gcoid=clearance:xblk:003106:gco|authorizedby2|INR Access Authorized By|txt:txt|0x00",
"entity:gcoid=clearance:xblk:003107:gco|bureauexecutiveoffice|Bureau Exec Off Authorized Req|txt:txt|0x00",
"entity:gcoid=clearance:xblk:003108:gco|bureaudate|Bureau Exec Data|txt:txt|0x04",
"entity:gcoid=clearance:xblk:003109:gco|bureauauthorizedby|Bureau Authorized|txt:txt|0x00",
"entity:gcoid=clearance:xblk:00310a:gco|comments|Comments|txt:txt|0x00",
//new items:
"entity:gcoid=personal:xblk:000201:gco|ecfirstname|Emergency Contact First Name|txt:txt|0x00",
"entity:gcoid=personal:xblk:000202:gco|eclastname|Emergency Contact Last Name|txt:txt|0x00",
"entity:gcoid=personal:xblk:000203:gco|ecphone|Emergency Contact Phone|txt:txt|0x00",
"entity:addrid=home:cntry:address|homecountry|Home Country|txt:txt|0x00",
"entity:gcoid=general:xblk:002502:gco|affiliation|Applicant Affiliation|txt:txt|0x00",
"entity:gcoid=clearance:xblk:002306:gco|briefing|Received Security Briefing|txt:txt|0x00",
"entity:gcoid=general:xblk:002300:gco|applicantstatus|Applicant Status|txt:txt|0x00",
"entity:bioid=signature:jpgpic:biometric|SigPad_JPEG|Person Signature JPEG|b64:bin|0x00",
"entity:bioid=signature:desc:biometric|SigPad_DESC|Person Signature Desc|txt:txt|0x00",
"entity:bioid=signature:xblk:biometric|SigPad_SIGFILE|Person Signature File|b64:bin|0x00",
);

$_workflow_procids = array(
"dac" => array("sponsor", "fpcap", "doccap", "photocap", "ichk", "print", "encode", "ship", "activate", "token"),
);

// Include the email templates for selection
include_once("../../appconfig/email_templates.php");

// The email templates to use in this service
if (!defined("ET_SPONSOR_DAC"))
	define("ET_SPONSOR_DAC", "process_sponsor");
if (!defined("ET_REISSUE_DAC"))
	define("ET_REISSUE_DAC", "process_reissue");

?>