<?PHP
// $Id: config-carevrequest.php 774 2008-10-31 20:09:40Z hjackson $
// Service configuration file
//    xsvc-reqcr.xas?id=tokenacid
require_once("../appconfig/config-app.php");

// sets debug flag; if TRUE debug statments are written to debugout.txt (if it exists).
$_debug = FALSE;
$_debugcurl = FALSE;
$_logsdir = '/authentxlogs/debug/authentx';

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "carevrequestresult";
$_service_version = "1.2";

// These are required to launch the CA interface process
$_execdir = "/authentx/app/https/authentx/servicesasa/";
$_process = "php ".$_execdir."carevrequest-generic.php";

$_ca_certificate = "/authentx/app/certs/ca-bundle.crt";
$_ca_clientcertificate = "/authentx/app/certs/browser.PEM";
$_ca_clientpassword = "password";

//add the xca base dn 
// $axCaIssuerDn = array("cn=WidePoint ORC NFI 4,ou=TEST-ARC,ou=Certification Authorities,o=WidePoint,c=US", "cn=XTec PIV-I SSP Test CA1,ou=TEST-ARC,ou=Certification Authorities,o=XTec Incorporated,c=US");

// add xca issuer cert dn to revoke cert
$axCaIssuerDn = array("cn=WidePoint ORC NFI 4,ou=TEST-ARC,ou=Certification Authorities,o=WidePoint,c=US", "cn=XTec PIV-I SSP Test CA1,ou=TEST-ARC,ou=Certification Authorities,o=XTec Incorporated,c=US", "cn=XTec PIV-I Test2 CA 1,ou=TEST-ARC,ou=Certification Authorities,o=XTec Incorporated,c=US");


// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : multiple instance attribute. Signifies that the attribute is not to be replaced
//  0x02 : 
//  0x04 : date format conversion required from/to openldap format and MM-DD-YYYY format
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_db_elements = array (

);

// add xca issuer cert dn to revoke cert
// $axCaIssuerDn = array("cn=XTec PIV-I SSP Test CA1,ou=TEST-ARC,ou=Certification Authorities,o=XTec Incorporated,c=US", "cn=WidePoint ORC NFI 4,ou=Certification Authorities,o=WidePoint,c=US");

$_constant_elements = array (
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, keyflags) ),
// );
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server, '0': key generated by token.
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_key_map = array (
	"A000000308" => array (
		"9A" => array("5FC105", 0x00),
		"9C" => array("5FC10A", 0x00),
		"9D" => array("5FC10B", 0x00),
		"9E" => array("5FC101", 0x00),
	),
);

$_appletid = "A000000308";
$_keyid = array ('9A','9C','9D','9E');

$_cert_types = array
(
	"9A" => "PIV Authentication (9A)",
	"9C" => "PIV Digital Signature (9C)",
	"9D" => "PIV Encryption (9D)",
	"9E" => "PIV Card Authentication (9E)"
);

$_key_map_derived = array(
	"derivedcert" => array(
	"9A" => array("DCRT9A"),
	"9C" => array("DCRT9C"),
	),
);

?>