<?PHP
// $Id:$
// Service configuration file
//    xsvc-reqcr.xas?id=tokenacid

// The number domain from which to get new CN numbers for the request
define("AUTHENTXCREQNUM", 	"00000000100000007000000060000002");

require_once("../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "reqcrresult";
$_service_version = "1.3";

// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : multiple instance attribute. Signifies that the attribute is not to be replaced
//  0x02 : 
//  0x04 : date format conversion required from/to openldap format and MM-DD-YYYY format
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_db_elements = array (
"entity:firstname:entity|firstname|x|txt:txt|0x00",
"entity:mi:entity|mi|x|txt:txt|0x00",
"entity:lastname:entity|lastname|x|txt:txt|0x00",
"entity:suffix:entity|suffix|x|txt:txt|0x00",
"token:gcoid=A000000308.5fc102:xblk:000030:gco|altname|x|txt:txt|0x00",
);

$_constant_elements = array (
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, keyflags) ),
// );
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server, '0': key generated by token.
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_key_map = array (
"A000000308" => array (
"9A" => array("5FC105", 0x00),
"9C" => array("5FC10A", 0x00),
"9D" => array("5FC10B", 0x00),
"9E" => array("5FC101", 0x00),
),
);

?>