<?PHP
// $Id: config-getcert.php 105 2008-11-18 01:44:38Z gswan $
// Service configuration file
//    xsvc-reqcr.xas?id=tokenacid
// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : MULTI
//  0x02 : 
//  0x04 : Date formatting required from/to LDAP format to MM-DD-YYYY format.
//  0x08 : Nosave. Data is not saved to the database.
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
//  0x100:
//	0x200: The element is to be encrypted/decrypted for database storage

require_once("../../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "getcertresult";
$_service_version = "1.0";

$_db_elements = array (
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, keyflags) ),
// );
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server, '0': key generated by token.
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_key_map = array (
"A000000308" => array (
"9A" => array("5FC105", 0x00),
"9C" => array("5FC10A", 0x00),
"9D" => array("5FC10B", 0x00),
"9E" => array("5FC101", 0x00),
),
);

?>