<?PHP
// $Id: config-requestescrow.php 105 2008-11-18 01:44:38Z gswan $
// Service configuration file
//    xsvc-requestescrow.xas?id=tokenacid

require_once("../../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "requestescrowresult";
$_service_version = "1.0";

// These are required to launch the CA interface process
$_execdir = "/authentx/app/https/".$site."/servicesasa/pivi";
$_process = "php -f ".$_execdir."/carequest-xcmp.php";
// this file should exist and be writable for it to be used by the process -- DEPRECATED
//$_reqcert_log_path = "carequest-escrow-gateway.log";

// set to true to request the 9D or false otherwise
$sendrequest_escrow = false;

// sets debug flag; if TRUE debug statments are written to debugout.txt (if it exists).
$_debug = TRUE;
// used to locate the email address for the request
$_emplid = "usaccess";
// group name to be used in certificate request.  If blank, dn_region is used.
$_sn_group = "authentx";
// domain extension for UPN
$_upn_domain = "@authentx.com";
// source of XML request sent to CA Gateway
$_origination = "authentx";

// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : multiple instance attribute. Signifies that the attribute is not to be replaced
//  0x02 : 
//  0x04 : date format conversion required from/to openldap format and MM-DD-YYYY format
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_db_elements = array (
"entity:firstname:entity|firstname|x|txt:txt|0x00",
"entity:mi:entity|mi|x|txt:txt|0x00",
"entity:lastname:entity|lastname|x|txt:txt|0x00",
"entity:suffix:entity|suffix|x|txt:txt:txt|0x00",
"entity:ediident:entity|ediident|x|txt:txt|0x00",
"entity:emplid=usaccess:email:employment|officeemail|x|txt:txt|0x00",
"entity:upn:entity|upn|x|txt:txt|0x00",
"token:upn:credential|tupn|x|txt:txt|0x00",
"token:tokenclass:credential|tokenclass|x|txt:txt|0x00",
"token:gcoid=A000000308.5fc102:xblk:000030:gco|fascn|x|txt:txt|0x00",
"token:gcoid=A000000308.5fc102:xblk:000034:gco|guid|x|txt:txt|0x00",
"token:gcoid=A000000308.5fc102:xblk:000035:gco|expdate|x|txt:txt|0x00",
"entity:gcoid=general:xblk:002502:gco|affiliation|x|txt:txt|0x00",
"token:gcoid=card:xblk:002091:gco|upnextension|x|txt:txt|0x00",
);

$_constant_elements = array (
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, keyflags) ),
// );
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server, '0': key generated by token.
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_key_map = array (
"A000000308" => array (
"9A" => array("5FC105", 0x00),
"9C" => array("5FC10A", 0x00),
"9D" => array("5FC10B", 0x00),
"9E" => array("5FC101", 0x00),
),
);

$_keyUsage = array (
"9A" => "9A",
"9C" => "9C",
"9D" => "9D",
"9E" => "9E",
);

// extension_flags: Bits to signify extensions to include in cert request
// NOTE: each cert must have at least one subjAltName
//  0x00 : nada
//  0x01 : FASCN as subject alternative name
//  0x02 : UPN as subject alternative name
//  0x04 : email address as subject alternative name
//  0x08 : guid/uuid as subject alternatve name (for piv-i)
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
$_certExtensions = array (
"9A" => 0x0E, // 0x07 for PIV, 0x0E for PIV-I
"9C" => 0x04, // 0x04
"9D" => 0x04, // 0x04
"9E" => 0x08,
);


// Configuration array for the DN coponents: oid, attribute_name, content_value.
// The componets to use in constructing the DN valure are listed in this array
// The content_value may be a function_name, which is called to resolve the actual value.
// "getrdnval" may be used to insert the region value from the user's authentx dn.

// Configuration array for the DN coponents: oid, attribute_name, content_value.
// The componets to use in constructing the DN valure are listed in this array
// The content_value may be a function_name, which is called to resolve the actual value.
// "getrdnval" may be used to insert the region value from the user's authentx dn.

$_baseDNconfig_pivi = array   // for test only
(
	array("\x55\x04\x06", "c", "US"),							// country
	array("\x55\x04\x0a", "o", "XTec PIV-I SSP"), 				// org
	array("\x55\x04\x0b", "ou", "XTec PIV-I Customers-General"),	// orgunit1
//	array("\x55\x04\x0b", "ou", "getrdnval"),					// orgunit2 
	array("\x55\x04\x0b", "ou", "Users"), 						// orgunit3
);

$_baseDNconfig_pivi_unafil = array 
(
	array("\x55\x04\x06", "c", "US"),
	array("\x55\x04\x0a", "o", "AuthentX"), 
	array("\x55\x04\x0b", "ou", "PIVI"),
//	array("\x55\x04\x0b", "ou", "getrdnval"),
	array("\x55\x04\x0b", "ou", "Entrust Shared Services CA"),
	array("\x55\x04\x0b", "ou", "Unaffiliated"), 
);

?>
