<?PHP
// $Id: config-carequest-entrust.php 271 2008-04-22 21:41:23Z atlas $
// Service configuration file
//    xsvc-reqcr.xas?id=tokenacid

require_once("../../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "gsacarequestresult";
$_service_version = "1.1";


//$_ca_url = "https://dev.authentx.com/cagateway/cagw-cagateway-frame.php"; // Gateway for Test 
//$_ca_url = "https://66.165.167.100/cagateway/cagw-cagateway-frame.php"; //  Gateway for Production (authentx.com)
//$_ca_url = "https://dev.authentx.com/cagateway-xtec/cagw-cagateway-frame.php"; // Gateway for XTEC 

$_ca_certificate = "/authentx/app/certs/ca-bundle.crt";
$_ca_clientcertificate = "/authentx/app/certs/browser.PEM";
$_ca_clientpassword = "password";

// sets debug flag; if TRUE debug statments are written to debugout.txt (if it exists).
$_debug = TRUE;
// used to locate the email address for the request
$_emplid = "usaccess";
// maximum certificate issuance validity period in days in PHP date() format
$_cert_max_issuance_days = "P1094D";

// group name to be used in certificate request.  If blank, dn_region is used.
$_sn_group = "XTec PIVI";  		// test CA = "XTec PIVI" 

$_max_key_history = 20;
$_max_oncard_escrow_certs = 20;

$_escrow_keys = array(
'9D', '82', '83', '84', '85', '86', '87', '88', '89', '8A', '8B',
'8C', '8D', '8E', '8F', '90', '91', '92', '93', '94', '95');

$_escrow_nums = array_flip($_escrow_keys);

//$_sn_group = "XTec PIV-I";  		// "XTec PIVI" old test CA
//$_sn_group = 'XTec XTec-Inc';		// use this for XTec Incorporated

// domain extension for UPN
$_upn_domain = "xtec.com";

// PIV-I Groups
//$_sn_group = 'XTec XTec-Inc';
//$_sn_group = 'XTec USAID-XTec';	// ? USAID PIV-I using XTec SSP
//$_sn_group = 'XTec FEMA';	
//$_sn_group = 'XTec Integ-Sci-Tech';	
//$_sn_group = 'XTec Oberthur';	
//$_sn_group = 'XTec Entrust';	
//$_sn_group = 'XTec Ffx-Cty-Fire';	
//$_sn_group = 'XTec Sunrise-Data-Sys';	
//$_sn_group = 'XTec FRBR';	

// source of XML request sent to CA Gateway
$_origination = "AUTHENTX";

// request for particular CA service (overrides _origination)
//$_carequest = 'ENT_NFI_DEMO_CA';  // ? PIV-I DEMO
//$_carequest = 'ENT_NFI_CA'; 		// ? PIV-I Production (legacy)

// certClassType - identifies the cert class type used by the CA to generate the correct
// certificate content (policies, etc). certType => [certClassType, certDef]
// This configuration items is optional, if not set, defaults will be used at the Gateway
/*
$_certClassType_map = array (
'9A' => array('xpki_pivi2k_3', 'Piv2KAuth'),
'9C' => array('xpki_pivi2k_3', 'Piv2KSign'),
'9D' => array('xpki_pivi2k_3', 'piv2KEnc'),
'9E' => array('xpki_pivi_cardauth', 'Piv2KCardAuth'),
);
*/

// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : multiple instance attribute. Signifies that the attribute is not to be replaced
//  0x02 : 
//  0x04 : date format conversion required from/to openldap format and MM-DD-YYYY format
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_db_elements = array (

);

$_constant_elements = array (
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, keyflags) ),
// );
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server, '0': key generated by token.
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

$_key_map = array (
	'A000000308' => array (
		'9A' => array('5FC105', 0x00),
		'9C' => array('5FC10A', 0x00),
		'9D' => array('5FC10B', 0x00),
		'9E' => array('5FC101', 0x00),

		// archived escrow keys
		'82' => array('5FC10D', 0x00),
		'83' => array('5FC10E', 0x00),
		'84' => array('5FC10F', 0x00),
		'85' => array('5FC110', 0x00),
		'86' => array('5FC111', 0x00),

		'87' => array('5FC112', 0x00),
		'88' => array('5FC113', 0x00),
		'89' => array('5FC114', 0x00),
		'8A' => array('5FC115', 0x00),
		'8B' => array('5FC116', 0x00),

		'8C' => array('5FC117', 0x00),
		'8D' => array('5FC118', 0x00),
		'8E' => array('5FC119', 0x00),
		'8F' => array('5FC11A', 0x00),
		'90' => array('5FC11B', 0x00),

		'91' => array('5FC11C', 0x00),
		'92' => array('5FC11D', 0x00),
		'93' => array('5FC11E', 0x00),
		'94' => array('5FC11F', 0x00),
		'95' => array('5FC120', 0x00),
		),
	);

$_tokenclass_codes = array (
0 => "PIV",
1 => "PIVI",
2 => "FLAC",
3 => "FAC",
4 => "FAC2",
);
?>
