<?PHP
// $Id: config-initcard.php 105 2008-11-18 01:44:38Z gswan $
// Service configuration file
//    xsvc-reqcr.xas?id=tokenacid

require_once("../../appconfig/config-app.php");

$_cred_basedn = $ldap_authcred.",credentials=authentx,ounit=credentials,".$ldap_treetop;
$_token_basedn = $ldap_credentials.",ounit=credentials,".$ldap_treetop;
$_service_envelope = "initcardresult";
$_service_version = "1.0";

// config array:
// source spec | xml tag | caption | conversion options | flags
// source spec: same as in form configuration.
// xml tag: the tag identifying the item in the incoming xml data
// form caption: the caption, not used in this service. Here for compatibility only.
// conversion options: delimited options to signify modification of the data:
//  XMLreq format : database format : extension parameters 
//      txt       :     txt                           = no conversion performed
//      b64       :     b64                           = Base64 format, no conversion performed
//      b64       :     bin                           = Base64 to/from binary conversion
//      hex       :     bin                           = hex characters to/from binary conversion
//      b64       :     hex                           = Base64 to/from hex characters conversion
// flags: Bits to signify extension operations
//  0x00 : no extension required
//  0x01 : MULTI
//  0x02 : 
//  0x04 : Date formatting required from/to LDAP format to MM-DD-YYYY format.
//  0x08 : Nosave. Data is not saved to the database.
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :
//  0x100:
//	0x200: The element is to be encrypted/decrypted for database storage

$_db_elements = array (
"token:gcoid=A000000308.5FC102:xblk:000030:gco|fascn|x|bin:bin|0x00",
"token:gcoid=A000000308.5FC102:xblk:000034:gco|guid|x|bin:bin|0x00",
"token:gcoid=A000000308.5FC102:xblk:000035:gco|expdate|x|txt:txt|0x00",
"token:gcoid=card:upin:gco|userpin|x|txt:txt|0x00",
);

$_constant_elements = array (
"defaultPUK" => "0000000000000000",
"defaultPIN" => "0000000000000000",
//"defaultCMK" => "101112131415161718191a1b1c1d1e1f",
"defaultCMK" => "101112131415161718191a1b1c1d1e1f1011121314151617", // new oberthurBAPcards dos, nsf
);

$_constant_elements_gemalto = array (
"defaultPUK" => "31323334FFFFFFFF",
"defaultPIN" => "31323334FFFFFFFF",
"defaultCMK" => "161259830304733788323182057204308058897889748263",	// dhs
);

$_constant_elements_gemalto_retkey = array (
"defaultPUK" => "31323334FFFFFFFF",
"defaultPIN" => "31323334FFFFFFFF",
"defaultCMK" => "161259830304733788323182057204308058897889748263",	// dhs
);

// Maps keys, containers and applets as well as the origin.
// $_key_map[$appletid][$keyid][0] = $keycontainer
// $_key_map[$appletid][$keyid][1] = $keyflags
// _key_map = array (
// appletid => 
// array( keyid => array(keycontainer, algorithmid, keyflags) ),
// );
// algorithmid:
// 0x01: 3DES-16bytekey-ECB
// 0x06: RSA-1024
// 0x07: RSA-2048
// keyflags: Bits to signify key features
//  0x00 : 
//  0x01 : '1': key generated by server (escrow), '0': key generated by token (token).
//  0x02 : 
//  0x04 : 
//  0x10 :
//  0x20 :
//  0x40 :
//  0x80 :

//key map now stored in config-keymaps.php

?>
